// NurseAcademy Module - Shared Data

export const courses = [
  {
    id: "course-1",
    title: "Advanced Emergency Nursing Protocols",
    description:
      "Master advanced emergency nursing protocols including triage systems, resuscitation procedures, and critical care management in resource-limited settings common across Nigerian healthcare facilities.",
    category: "Emergency Nursing",
    level: "Advanced",
    duration: "8 weeks",
    cpdPoints: 15,
    rating: 4.9,
    reviewCount: 234,
    price: 25000,
    currency: "NGN",
    instructor: "Dr. Chinedu Eze",
    instructorTitle: "Consultant Emergency Physician, LUTH",
    thumbnail: "",
    language: "English",
    enrolled: true,
    progress: 65,
    modules: [
      { id: "m1-1", title: "Introduction to Advanced Emergency Care", type: "Video", duration: "45 min" },
      { id: "m1-2", title: "Triage Systems: START & Modified START", type: "Video", duration: "60 min" },
      { id: "m1-3", title: "Primary & Secondary Survey", type: "Text", duration: "30 min" },
      { id: "m1-4", title: "Airway Management in Emergency", type: "Video", duration: "50 min" },
      { id: "m1-5", title: "Module 1 Assessment", type: "Quiz", duration: "20 min" },
      { id: "m1-6", title: "Cardiac Emergencies & ACLS", type: "Video", duration: "75 min" },
      { id: "m1-7", title: "Trauma Assessment & Management", type: "Video", duration: "65 min" },
      { id: "m1-8", title: "Shock Recognition & Resuscitation", type: "Text", duration: "40 min" },
      { id: "m1-9", title: "Module 2 Assessment", type: "Quiz", duration: "25 min" },
    ],
    featured: true,
    students: 1520,
  },
  {
    id: "course-2",
    title: "Maternal Health & Obstetric Nursing",
    description:
      "Comprehensive training in maternal health nursing with focus on antenatal care, safe delivery practices, and postpartum management aligned with WHO and FMoN guidelines.",
    category: "Maternal Health",
    level: "Intermediate",
    duration: "6 weeks",
    cpdPoints: 10,
    rating: 4.7,
    reviewCount: 189,
    price: 0,
    currency: "NGN",
    instructor: "Matron Folake Adeyemi",
    instructorTitle: "Senior Matron, Obstetrics Ward, LUTH",
    thumbnail: "",
    language: "English",
    enrolled: false,
    progress: 0,
    modules: [
      { id: "m2-1", title: "Antenatal Care Essentials", type: "Video", duration: "55 min" },
      { id: "m2-2", title: "Normal Labour & Delivery", type: "Video", duration: "70 min" },
      { id: "m2-3", title: "Postpartum Care & Complications", type: "Text", duration: "35 min" },
      { id: "m2-4", title: "Obstetric Emergencies", type: "Video", duration: "60 min" },
      { id: "m2-5", title: "Module Assessment", type: "Quiz", duration: "20 min" },
    ],
    featured: true,
    students: 2100,
  },
  {
    id: "course-3",
    title: "Clinical Pharmacology for Nurses",
    description:
      "Deep dive into pharmacology essential for nursing practice including drug classifications, dosage calculations, adverse reactions, and Nigerian National Drug Policy.",
    category: "Pharmacology",
    level: "Intermediate",
    duration: "10 weeks",
    cpdPoints: 12,
    rating: 4.6,
    reviewCount: 156,
    price: 18000,
    currency: "NGN",
    instructor: "Dr. Aisha Bello",
    instructorTitle: "Clinical Pharmacist & Lecturer, ABU Zaria",
    thumbnail: "",
    language: "English",
    enrolled: true,
    progress: 30,
    modules: [
      { id: "m3-1", title: "Principles of Pharmacology", type: "Video", duration: "50 min" },
      { id: "m3-2", title: "Drug Classifications & Scheduling", type: "Text", duration: "40 min" },
      { id: "m3-3", title: "Dosage Calculations Workshop", type: "Video", duration: "60 min" },
      { id: "m3-4", title: "Common Medications in Nigerian Practice", type: "Video", duration: "55 min" },
      { id: "m3-5", title: "Adverse Drug Reactions", type: "Text", duration: "30 min" },
      { id: "m3-6", title: "Assessment", type: "Quiz", duration: "30 min" },
    ],
    featured: false,
    students: 890,
  },
  {
    id: "course-4",
    title: "Nursing Leadership & Management",
    description:
      "Develop leadership skills essential for nursing management roles. Learn about healthcare team management, quality improvement, and policy development in the Nigerian healthcare context.",
    category: "Leadership",
    level: "Advanced",
    duration: "8 weeks",
    cpdPoints: 14,
    rating: 4.8,
    reviewCount: 145,
    price: 30000,
    currency: "NGN",
    instructor: "Prof. Ngozi Okafor",
    instructorTitle: "Professor of Nursing, University of Ibadan",
    thumbnail: "",
    language: "English",
    enrolled: false,
    progress: 0,
    modules: [
      { id: "m4-1", title: "Leadership Theories in Nursing", type: "Video", duration: "45 min" },
      { id: "m4-2", title: "Healthcare Team Management", type: "Video", duration: "55 min" },
      { id: "m4-3", title: "Quality Improvement in Nursing", type: "Text", duration: "35 min" },
      { id: "m4-4", title: "Policy & Advocacy", type: "Video", duration: "50 min" },
      { id: "m4-5", title: "Financial Management", type: "Text", duration: "40 min" },
      { id: "m4-6", title: "Final Assessment", type: "Quiz", duration: "30 min" },
    ],
    featured: false,
    students: 670,
  },
  {
    id: "course-5",
    title: "Pediatric Nursing Essentials",
    description:
      "Essential skills for pediatric nursing including child assessment, common childhood illnesses in Nigeria, immunization schedules, and family-centered care approaches.",
    category: "Pediatric Nursing",
    level: "Beginner",
    duration: "6 weeks",
    cpdPoints: 8,
    rating: 4.5,
    reviewCount: 210,
    price: 0,
    currency: "NGN",
    instructor: "Sr. Mary Okonkwo",
    instructorTitle: "Pediatric Nurse Specialist, UNTH Enugu",
    thumbnail: "",
    language: "English",
    enrolled: false,
    progress: 0,
    modules: [
      { id: "m5-1", title: "Growth & Development Assessment", type: "Video", duration: "50 min" },
      { id: "m5-2", title: "Common Childhood Illnesses", type: "Video", duration: "60 min" },
      { id: "m5-3", title: "Immunization Schedules (NPI)", type: "Text", duration: "25 min" },
      { id: "m5-4", title: "Family-Centered Care", type: "Video", duration: "40 min" },
      { id: "m5-5", title: "Assessment", type: "Quiz", duration: "20 min" },
    ],
    featured: true,
    students: 1800,
  },
  {
    id: "course-6",
    title: "Infection Prevention & Control",
    description:
      "Comprehensive IPC training based on NCDC guidelines. Covers hand hygiene, PPE usage, isolation protocols, and outbreak management in Nigerian healthcare facilities.",
    category: "Infection Control",
    level: "Beginner",
    duration: "4 weeks",
    cpdPoints: 6,
    rating: 4.9,
    reviewCount: 320,
    price: 0,
    currency: "NGN",
    instructor: "Dr. Ngozi Okafor",
    instructorTitle: "IPC Specialist, NCDC",
    thumbnail: "",
    language: "English",
    enrolled: true,
    progress: 100,
    modules: [
      { id: "m6-1", title: "Principles of IPC", type: "Video", duration: "40 min" },
      { id: "m6-2", title: "Hand Hygiene & PPE", type: "Video", duration: "35 min" },
      { id: "m6-3", title: "Isolation Precautions", type: "Text", duration: "30 min" },
      { id: "m6-4", title: "Outbreak Management", type: "Video", duration: "50 min" },
      { id: "m6-5", title: "Assessment", type: "Quiz", duration: "20 min" },
    ],
    featured: false,
    students: 3200,
  },
  {
    id: "course-7",
    title: "Surgical Nursing & Perioperative Care",
    description:
      "Master perioperative nursing from pre-operative assessment through intra-operative care to post-operative management with emphasis on patient safety and surgical site infection prevention.",
    category: "Surgical Nursing",
    level: "Intermediate",
    duration: "8 weeks",
    cpdPoints: 11,
    rating: 4.6,
    reviewCount: 132,
    price: 22000,
    currency: "NGN",
    instructor: "Dr. Emeka Obi",
    instructorTitle: "Chief Theatre Nurse, UCH Ibadan",
    thumbnail: "",
    language: "English",
    enrolled: false,
    progress: 0,
    modules: [
      { id: "m7-1", title: "Pre-operative Assessment", type: "Video", duration: "55 min" },
      { id: "m7-2", title: "Intra-operative Nursing Care", type: "Video", duration: "65 min" },
      { id: "m7-3", title: "Post-operative Management", type: "Text", duration: "40 min" },
      { id: "m7-4", title: "Surgical Site Infection Prevention", type: "Video", duration: "45 min" },
      { id: "m7-5", title: "Assessment", type: "Quiz", duration: "25 min" },
    ],
    featured: false,
    students: 560,
  },
  {
    id: "course-8",
    title: "Mental Health Nursing Practice",
    description:
      "Understanding mental health nursing in the Nigerian context including cultural considerations, therapeutic communication, common psychiatric disorders, and community mental health approaches.",
    category: "Mental Health",
    level: "Intermediate",
    duration: "7 weeks",
    cpdPoints: 9,
    rating: 4.4,
    reviewCount: 98,
    price: 15000,
    currency: "NGN",
    instructor: "Dr. Aisha Bello",
    instructorTitle: "Psychiatric Nurse Specialist, ABU Zaria",
    thumbnail: "",
    language: "English",
    enrolled: false,
    progress: 0,
    modules: [
      { id: "m8-1", title: "Mental Health Fundamentals", type: "Video", duration: "50 min" },
      { id: "m8-2", title: "Therapeutic Communication", type: "Video", duration: "45 min" },
      { id: "m8-3", title: "Psychiatric Disorders", type: "Text", duration: "40 min" },
      { id: "m8-4", title: "Community Mental Health", type: "Video", duration: "55 min" },
      { id: "m8-5", title: "Assessment", type: "Quiz", duration: "20 min" },
    ],
    featured: false,
    students: 430,
  },
  {
    id: "course-9",
    title: "Community Health Nursing",
    description:
      "Essential community health nursing skills including primary healthcare delivery, health education, epidemiology, and the National Health Insurance Scheme (NHIS) framework.",
    category: "Community Health",
    level: "Beginner",
    duration: "5 weeks",
    cpdPoints: 7,
    rating: 4.5,
    reviewCount: 167,
    price: 0,
    currency: "NGN",
    instructor: "Mrs. Bimpe Alakija",
    instructorTitle: "Community Health Coordinator, Ogun State",
    thumbnail: "",
    language: "English",
    enrolled: true,
    progress: 45,
    modules: [
      { id: "m9-1", title: "Primary Healthcare Principles", type: "Video", duration: "45 min" },
      { id: "m9-2", title: "Health Education Strategies", type: "Video", duration: "40 min" },
      { id: "m9-3", title: "Epidemiology Basics", type: "Text", duration: "30 min" },
      { id: "m9-4", title: "NHIS Framework", type: "Video", duration: "35 min" },
      { id: "m9-5", title: "Assessment", type: "Quiz", duration: "20 min" },
    ],
    featured: true,
    students: 1450,
  },
  {
    id: "course-10",
    title: "Critical Care Nursing Advanced",
    description:
      "Advanced critical care nursing for ICU settings. Covers ventilator management, hemodynamic monitoring, multi-organ dysfunction, and critical care pharmacology.",
    category: "Critical Care",
    level: "Advanced",
    duration: "12 weeks",
    cpdPoints: 18,
    rating: 4.8,
    reviewCount: 89,
    price: 35000,
    currency: "NGN",
    instructor: "Dr. Chinedu Eze",
    instructorTitle: "ICU Consultant, LUTH",
    thumbnail: "",
    language: "English",
    enrolled: false,
    progress: 0,
    modules: [
      { id: "m10-1", title: "ICU Fundamentals", type: "Video", duration: "60 min" },
      { id: "m10-2", title: "Ventilator Management", type: "Video", duration: "70 min" },
      { id: "m10-3", title: "Hemodynamic Monitoring", type: "Video", duration: "55 min" },
      { id: "m10-4", title: "Multi-Organ Dysfunction", type: "Text", duration: "45 min" },
      { id: "m10-5", title: "Critical Care Pharmacology", type: "Video", duration: "65 min" },
      { id: "m10-6", title: "Final Assessment", type: "Quiz", duration: "40 min" },
    ],
    featured: false,
    students: 320,
  },
  {
    id: "course-11",
    title: "Nursing Research & Evidence-Based Practice",
    description:
      "Learn research methodology and evidence-based practice skills to contribute to nursing knowledge. Includes proposal writing, data analysis, and publishing in Nigerian journals.",
    category: "Research",
    level: "Advanced",
    duration: "8 weeks",
    cpdPoints: 12,
    rating: 4.3,
    reviewCount: 76,
    price: 20000,
    currency: "NGN",
    instructor: "Prof. Ngozi Okafor",
    instructorTitle: "Professor of Nursing, University of Ibadan",
    thumbnail: "",
    language: "English",
    enrolled: false,
    progress: 0,
    modules: [
      { id: "m11-1", title: "Research Fundamentals", type: "Video", duration: "50 min" },
      { id: "m11-2", title: "Proposal Writing", type: "Text", duration: "45 min" },
      { id: "m11-3", title: "Data Collection & Analysis", type: "Video", duration: "65 min" },
      { id: "m11-4", title: "Publishing Your Research", type: "Video", duration: "40 min" },
      { id: "m11-5", title: "Assessment", type: "Quiz", duration: "30 min" },
    ],
    featured: false,
    students: 280,
  },
];

export const courseCategories = [
  "All",
  "Emergency Nursing",
  "Maternal Health",
  "Pharmacology",
  "Leadership",
  "Pediatric Nursing",
  "Infection Control",
  "Surgical Nursing",
  "Mental Health",
  "Community Health",
  "Critical Care",
  "Research",
];

export const courseLevels = ["All", "Beginner", "Intermediate", "Advanced"];

export const simulations = [
  {
    id: "sim-1",
    title: "Post-Partum Hemorrhage Emergency",
    scenarioType: "Emergency",
    difficulty: "Hard",
    avgScore: 72,
    completions: 845,
    duration: "25 min",
    description:
      "Manage a post-partum hemorrhage emergency in a resource-limited maternity ward. Make critical decisions about interventions, medications, and when to escalate care.",
    skills: ["Emergency Care", "Maternal Health", "Medication Admin"],
  },
  {
    id: "sim-2",
    title: "Malaria Treatment Protocol — Pediatric Case",
    scenarioType: "Clinical Decision",
    difficulty: "Medium",
    avgScore: 78,
    completions: 1230,
    duration: "20 min",
    description:
      "Assess and manage a 4-year-old child presenting with severe malaria. Apply WHO treatment guidelines and Nigerian National Malaria Control Programme protocols.",
    skills: ["Pediatric Assessment", "Pharmacology", "Clinical Decision"],
  },
  {
    id: "sim-3",
    title: "Pediatric Assessment — Febrile Convulsion",
    scenarioType: "Clinical Decision",
    difficulty: "Medium",
    avgScore: 81,
    completions: 950,
    duration: "18 min",
    description:
      "Assess a toddler presenting with febrile convulsions. Conduct proper assessment, stabilize the patient, and determine the underlying cause.",
    skills: ["Pediatric Assessment", "Emergency Care", "Patient Education"],
  },
  {
    id: "sim-4",
    title: "Breaking Bad News — Terminal Diagnosis",
    scenarioType: "Communication",
    difficulty: "Expert",
    avgScore: 65,
    completions: 567,
    duration: "30 min",
    description:
      "Navigate the difficult conversation of informing a family about a terminal cancer diagnosis. Practice empathetic communication, cultural sensitivity, and support strategies.",
    skills: ["Communication", "Palliative Care", "Cultural Competency"],
  },
  {
    id: "sim-5",
    title: "Ethical Dilemma — Resource Allocation",
    scenarioType: "Ethical Dilemma",
    difficulty: "Expert",
    avgScore: 60,
    completions: 432,
    duration: "35 min",
    description:
      "Face an ethical dilemma when two patients need the only available ventilator. Apply ethical principles, consult with team, and make defensible decisions.",
    skills: ["Ethics", "Leadership", "Critical Care"],
  },
  {
    id: "sim-6",
    title: "Road Traffic Accident — Mass Casualty Triage",
    scenarioType: "Emergency",
    difficulty: "Hard",
    avgScore: 68,
    completions: 789,
    duration: "22 min",
    description:
      "Perform START triage on multiple victims from a road traffic accident. Prioritize care and manage limited resources effectively.",
    skills: ["Emergency Triage", "Leadership", "Critical Thinking"],
  },
  {
    id: "sim-7",
    title: "Diabetic Ketoacidosis Management",
    scenarioType: "Clinical Decision",
    difficulty: "Hard",
    avgScore: 70,
    completions: 654,
    duration: "25 min",
    description:
      "Manage a patient presenting with diabetic ketoacidosis. Administer insulin protocol, monitor electrolytes, and prevent complications.",
    skills: ["Medication Admin", "Clinical Assessment", "Critical Care"],
  },
  {
    id: "sim-8",
    title: "Lassa Fever Isolation Protocol",
    scenarioType: "Emergency",
    difficulty: "Medium",
    avgScore: 76,
    completions: 543,
    duration: "20 min",
    description:
      "Implement isolation and infection control measures for a suspected Lassa fever case. Apply NCDC guidelines and protect healthcare workers.",
    skills: ["Infection Control", "Isolation Protocols", "PPE Usage"],
  },
  {
    id: "sim-9",
    title: "Patient Handover Communication",
    scenarioType: "Communication",
    difficulty: "Easy",
    avgScore: 85,
    completions: 1567,
    duration: "15 min",
    description:
      "Practice effective SBAR handover communication between shifts. Ensure continuity of care and prevent information gaps.",
    skills: ["Communication", "Documentation", "Teamwork"],
  },
];

export const simulationTypes = ["All", "Emergency", "Clinical Decision", "Communication", "Ethical Dilemma"];
export const simulationDifficulties = ["All", "Easy", "Medium", "Hard", "Expert"];

export const myLearningInProgress = [
  {
    id: "course-1",
    title: "Advanced Emergency Nursing Protocols",
    category: "Emergency Nursing",
    progress: 65,
    lastModule: "Cardiac Emergencies & ACLS",
    nextModule: "Trauma Assessment & Management",
    cpdPoints: 15,
    enrolledDate: "2024-09-15",
  },
  {
    id: "course-3",
    title: "Clinical Pharmacology for Nurses",
    category: "Pharmacology",
    progress: 30,
    lastModule: "Drug Classifications & Scheduling",
    nextModule: "Dosage Calculations Workshop",
    cpdPoints: 12,
    enrolledDate: "2024-10-01",
  },
  {
    id: "course-9",
    title: "Community Health Nursing",
    category: "Community Health",
    progress: 45,
    lastModule: "Health Education Strategies",
    nextModule: "Epidemiology Basics",
    cpdPoints: 7,
    enrolledDate: "2024-10-20",
  },
];

export const myLearningCompleted = [
  {
    id: "course-6",
    title: "Infection Prevention & Control",
    category: "Infection Control",
    progress: 100,
    completedDate: "2024-08-30",
    cpdPoints: 6,
    certificateId: "CERT/NOS/2024/IPC-001",
  },
  {
    id: "course-bls",
    title: "BLS Recertification Course",
    category: "Emergency Nursing",
    progress: 100,
    completedDate: "2024-07-15",
    cpdPoints: 4,
    certificateId: "CERT/NOS/2024/BLS-042",
  },
];

export const certificates = [
  {
    id: "cert-1",
    courseName: "Infection Prevention & Control",
    completedDate: "2024-08-30",
    cpdPoints: 6,
    certificateId: "CERT/NOS/2024/IPC-001",
    verificationHash: "0xa1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0",
    instructor: "Dr. Ngozi Okafor",
  },
  {
    id: "cert-2",
    courseName: "BLS Recertification Course",
    completedDate: "2024-07-15",
    cpdPoints: 4,
    certificateId: "CERT/NOS/2024/BLS-042",
    verificationHash: "0xf9e8d7c6b5a4f3e2d1c0b9a8f7e6d5c4b3a2f1e0",
    instructor: "Dr. Chinedu Eze",
  },
  {
    id: "cert-3",
    courseName: "Wound Care Management Certificate",
    completedDate: "2024-05-20",
    cpdPoints: 8,
    certificateId: "CERT/NOS/2024/WCM-017",
    verificationHash: "0x1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b",
    instructor: "Sr. Mary Okonkwo",
  },
  {
    id: "cert-4",
    courseName: "Digital Health Fundamentals",
    completedDate: "2024-03-10",
    cpdPoints: 5,
    certificateId: "CERT/NOS/2024/DHF-089",
    verificationHash: "0xb1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0",
    instructor: "Mr. Tunde Bakare",
  },
  {
    id: "cert-5",
    courseName: "Patient Safety & Quality Improvement",
    completedDate: "2024-01-22",
    cpdPoints: 7,
    certificateId: "CERT/NOS/2024/PSQ-034",
    verificationHash: "0xc2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1",
    instructor: "Prof. Ngozi Okafor",
  },
];
