// CareGrid Module Data

export interface Facility {
  id: string;
  name: string;
  type: "Teaching Hospital" | "Federal Medical Centre" | "Specialist Hospital" | "General Hospital" | "Primary Health Centre" | "Private Hospital";
  state: string;
  lga: string;
  address: string;
  bedCapacity: number;
  occupiedBeds: number;
  isVerified: boolean;
  hasEmergency: boolean;
  phone: string;
  email: string;
  specialties: string[];
  rating: number;
}

export const facilities: Facility[] = [
  {
    id: "F001",
    name: "Lagos University Teaching Hospital",
    type: "Teaching Hospital",
    state: "Lagos",
    lga: "Lagos Island",
    address: "Idi-Araba, Mushin, Lagos",
    bedCapacity: 750,
    occupiedBeds: 682,
    isVerified: true,
    hasEmergency: true,
    phone: "+234-1-497-2200",
    email: "info@luth.org.ng",
    specialties: ["Cardiology", "Neurosurgery", "Oncology", "Nephrology"],
    rating: 4.8,
  },
  {
    id: "F002",
    name: "Federal Medical Centre, Abuja",
    type: "Federal Medical Centre",
    state: "FCT",
    lga: "Abuja Municipal",
    address: "Wuse Zone 4, Abuja",
    bedCapacity: 500,
    occupiedBeds: 435,
    isVerified: true,
    hasEmergency: true,
    phone: "+234-9-523-3300",
    email: "info@fmcabuja.org.ng",
    specialties: ["Orthopedics", "Pediatrics", "Obstetrics", "General Surgery"],
    rating: 4.5,
  },
  {
    id: "F003",
    name: "University College Hospital, Ibadan",
    type: "Teaching Hospital",
    state: "Oyo",
    lga: "Ibadan North",
    address: "Queen Elizabeth Road, Ibadan",
    bedCapacity: 850,
    occupiedBeds: 790,
    isVerified: true,
    hasEmergency: true,
    phone: "+234-2-241-0088",
    email: "info@uch-ibadan.org.ng",
    specialties: ["Cardiology", "Dermatology", "Psychiatry", "Radiology"],
    rating: 4.7,
  },
  {
    id: "F004",
    name: "Ahmadu Bello University Teaching Hospital",
    type: "Teaching Hospital",
    state: "Kaduna",
    lga: "Zaria",
    address: "Shika, Zaria, Kaduna",
    bedCapacity: 600,
    occupiedBeds: 510,
    isVerified: true,
    hasEmergency: true,
    phone: "+234-62-301-111",
    email: "info@abuth.org.ng",
    specialties: ["Infectious Disease", "Pediatrics", "Ophthalmology", "ENT"],
    rating: 4.3,
  },
  {
    id: "F005",
    name: "University of Nigeria Teaching Hospital",
    type: "Teaching Hospital",
    state: "Enugu",
    lga: "Enugu East",
    address: "Ituku-Ozalla, Enugu",
    bedCapacity: 650,
    occupiedBeds: 580,
    isVerified: true,
    hasEmergency: true,
    phone: "+234-42-300-555",
    email: "info@unth.org.ng",
    specialties: ["Neurosurgery", "Cardiothoracic", "Urology", "Hematology"],
    rating: 4.6,
  },
  {
    id: "F006",
    name: "Lagos State General Hospital",
    type: "General Hospital",
    state: "Lagos",
    lga: "Lagos Mainland",
    address: "Broad Street, Lagos Island",
    bedCapacity: 300,
    occupiedBeds: 265,
    isVerified: true,
    hasEmergency: true,
    phone: "+234-1-263-0400",
    email: "info@lsghlagos.org.ng",
    specialties: ["General Medicine", "Surgery", "Pediatrics", "OB/GYN"],
    rating: 4.0,
  },
  {
    id: "F007",
    name: "National Hospital, Abuja",
    type: "Specialist Hospital",
    state: "FCT",
    lga: "Central District",
    address: "Garki, Abuja",
    bedCapacity: 400,
    occupiedBeds: 340,
    isVerified: true,
    hasEmergency: true,
    phone: "+234-9-523-2600",
    email: "info@nationalhospital.gov.ng",
    specialties: ["Renal Transplant", "Radiotherapy", "Nuclear Medicine", "Trauma"],
    rating: 4.4,
  },
  {
    id: "F008",
    name: "Rivers State University Teaching Hospital",
    type: "Teaching Hospital",
    state: "Rivers",
    lga: "Port Harcourt",
    address: "East-West Road, Port Harcourt",
    bedCapacity: 450,
    occupiedBeds: 380,
    isVerified: true,
    hasEmergency: true,
    phone: "+234-84-232-000",
    email: "info@rsuth.org.ng",
    specialties: ["Burns & Plastic", "Orthopedics", "OB/GYN", "Pediatrics"],
    rating: 4.2,
  },
  {
    id: "F009",
    name: "Garki Primary Health Centre",
    type: "Primary Health Centre",
    state: "FCT",
    lga: "Garki",
    address: "Garki Area 3, Abuja",
    bedCapacity: 50,
    occupiedBeds: 42,
    isVerified: false,
    hasEmergency: false,
    phone: "+234-9-314-2200",
    email: "info@garkiphc.gov.ng",
    specialties: ["General Practice", "Immunization", "Antenatal Care", "Family Planning"],
    rating: 3.8,
  },
  {
    id: "F010",
    name: "Reddington Hospital",
    type: "Private Hospital",
    state: "Lagos",
    lga: "Victoria Island",
    address: "12 Harvey Road, Victoria Island, Lagos",
    bedCapacity: 120,
    occupiedBeds: 98,
    isVerified: true,
    hasEmergency: true,
    phone: "+234-1-460-1000",
    email: "info@reddingtonhospital.com",
    specialties: ["Cardiology", "Oncology", "Dialysis", "Executive Health"],
    rating: 4.6,
  },
];

export interface Referral {
  id: string;
  patientName: string;
  patientAge: number;
  patientGender: "Male" | "Female";
  fromFacility: string;
  toFacility: string;
  urgency: "Routine" | "Urgent" | "STAT";
  status: "Pending" | "Accepted" | "In Transit" | "Completed";
  nurseAssigned: string;
  reason: string;
  date: string;
  estimatedArrival?: string;
}

export const referrals: Referral[] = [
  {
    id: "REF-2024-001",
    patientName: "Chinedu Okafor",
    patientAge: 45,
    patientGender: "Male",
    fromFacility: "Lagos State General Hospital",
    toFacility: "Lagos University Teaching Hospital",
    urgency: "STAT",
    status: "In Transit",
    nurseAssigned: "Nurse Adaeze Okonkwo",
    reason: "Acute myocardial infarction requiring cardiac catheterization",
    date: "2024-03-15",
    estimatedArrival: "45 min",
  },
  {
    id: "REF-2024-002",
    patientName: "Fatima Abdullahi",
    patientAge: 28,
    patientGender: "Female",
    fromFacility: "Garki Primary Health Centre",
    toFacility: "National Hospital, Abuja",
    urgency: "Urgent",
    status: "Accepted",
    nurseAssigned: "Nurse Binta Mohammed",
    reason: "High-risk pregnancy with preeclampsia",
    date: "2024-03-15",
    estimatedArrival: "1 hr",
  },
  {
    id: "REF-2024-003",
    patientName: "Emeka Nwankwo",
    patientAge: 32,
    patientGender: "Male",
    fromFacility: "Federal Medical Centre, Abuja",
    toFacility: "National Hospital, Abuja",
    urgency: "Urgent",
    status: "Pending",
    nurseAssigned: "Unassigned",
    reason: "Severe head injury from road traffic accident",
    date: "2024-03-14",
  },
  {
    id: "REF-2024-004",
    patientName: "Amina Bello",
    patientAge: 5,
    patientGender: "Female",
    fromFacility: "Garki Primary Health Centre",
    toFacility: "Federal Medical Centre, Abuja",
    urgency: "STAT",
    status: "In Transit",
    nurseAssigned: "Nurse Halima Yusuf",
    reason: "Severe malaria with cerebral involvement",
    date: "2024-03-14",
    estimatedArrival: "30 min",
  },
  {
    id: "REF-2024-005",
    patientName: "Olumide Adeyemi",
    patientAge: 60,
    patientGender: "Male",
    fromFacility: "Reddington Hospital",
    toFacility: "Lagos University Teaching Hospital",
    urgency: "Routine",
    status: "Completed",
    nurseAssigned: "Nurse Folake Williams",
    reason: "Post-operative follow-up for joint replacement",
    date: "2024-03-13",
  },
  {
    id: "REF-2024-006",
    patientName: "Blessing Eze",
    patientAge: 35,
    patientGender: "Female",
    fromFacility: "University of Nigeria Teaching Hospital",
    toFacility: "Federal Medical Centre, Abuja",
    urgency: "Routine",
    status: "Completed",
    nurseAssigned: "Nurse Chioma Nwosu",
    reason: "Dialysis transfer for chronic renal failure",
    date: "2024-03-12",
  },
  {
    id: "REF-2024-007",
    patientName: "Ibrahim Musa",
    patientAge: 50,
    patientGender: "Male",
    fromFacility: "Ahmadu Bello University Teaching Hospital",
    toFacility: "National Hospital, Abuja",
    urgency: "Urgent",
    status: "Accepted",
    nurseAssigned: "Nurse Aisha Kano",
    reason: "Suspected Lassa fever requiring isolation unit",
    date: "2024-03-15",
    estimatedArrival: "3 hrs",
  },
  {
    id: "REF-2024-008",
    patientName: "Chioma Obi",
    patientAge: 25,
    patientGender: "Female",
    fromFacility: "Rivers State University Teaching Hospital",
    toFacility: "University College Hospital, Ibadan",
    urgency: "Routine",
    status: "Pending",
    nurseAssigned: "Unassigned",
    reason: "Complex burn reconstruction referral",
    date: "2024-03-14",
  },
  {
    id: "REF-2024-009",
    patientName: "Tunde Bakare",
    patientAge: 40,
    patientGender: "Male",
    fromFacility: "Lagos State General Hospital",
    toFacility: "Reddington Hospital",
    urgency: "Urgent",
    status: "Pending",
    nurseAssigned: "Unassigned",
    reason: "Acute kidney injury requiring emergency dialysis",
    date: "2024-03-15",
  },
];

export interface Consultation {
  id: string;
  subject: string;
  type: "Video" | "Chat" | "Phone";
  nurseFrom: string;
  nurseTo: string;
  status: "Active" | "Scheduled" | "Completed" | "Cancelled";
  date: string;
  time: string;
  specialty: string;
  notes?: string;
}

export const consultations: Consultation[] = [
  {
    id: "CON-001",
    subject: "Neonatal Sepsis Management Protocol",
    type: "Video",
    nurseFrom: "Nurse Adaora Nwosu",
    nurseTo: "Dr. Ngozi Eze",
    status: "Active",
    date: "2024-03-15",
    time: "10:00 AM",
    specialty: "Neonatology",
    notes: "Discussing antibiotic stewardship for 3-day-old neonate",
  },
  {
    id: "CON-002",
    subject: "Trauma Triage Assessment",
    type: "Phone",
    nurseFrom: "Nurse Adaeze Okonkwo",
    nurseTo: "Nurse Emeka Okafor",
    status: "Scheduled",
    date: "2024-03-16",
    time: "2:00 PM",
    specialty: "Emergency",
  },
  {
    id: "CON-003",
    subject: "Post-Cesarean Wound Care",
    type: "Chat",
    nurseFrom: "Nurse Chioma Nwosu",
    nurseTo: "Nurse Adaora Nwosu",
    status: "Completed",
    date: "2024-03-14",
    time: "9:30 AM",
    specialty: "Obstetrics",
  },
  {
    id: "CON-004",
    subject: "Lassa Fever Isolation Protocol",
    type: "Video",
    nurseFrom: "Nurse Halima Yusuf",
    nurseTo: "Dr. Aminu Bello",
    status: "Active",
    date: "2024-03-15",
    time: "11:30 AM",
    specialty: "Infectious Disease",
  },
  {
    id: "CON-005",
    subject: "Pediatric Malaria Treatment",
    type: "Video",
    nurseFrom: "Nurse Folake Williams",
    nurseTo: "Nurse Binta Mohammed",
    status: "Scheduled",
    date: "2024-03-17",
    time: "3:00 PM",
    specialty: "Pediatrics",
  },
  {
    id: "CON-006",
    subject: "Diabetic Foot Ulcer Management",
    type: "Chat",
    nurseFrom: "Nurse Adaora Nwosu",
    nurseTo: "Nurse Adaeze Okonkwo",
    status: "Active",
    date: "2024-03-15",
    time: "1:00 PM",
    specialty: "Endocrinology",
  },
  {
    id: "CON-007",
    subject: "Sickle Cell Crisis Intervention",
    type: "Phone",
    nurseFrom: "Nurse Emeka Okafor",
    nurseTo: "Nurse Chioma Nwosu",
    status: "Completed",
    date: "2024-03-13",
    time: "4:00 PM",
    specialty: "Hematology",
  },
  {
    id: "CON-008",
    subject: "Ventilator Weaning Protocol",
    type: "Video",
    nurseFrom: "Nurse Binta Mohammed",
    nurseTo: "Dr. Ngozi Eze",
    status: "Scheduled",
    date: "2024-03-18",
    time: "10:30 AM",
    specialty: "Critical Care",
  },
];

export interface Article {
  id: string;
  title: string;
  category: string;
  author: string;
  authorTitle: string;
  evidenceLevel: "Level I" | "Level II" | "Level III" | "Level IV" | "Level V";
  readTime: string;
  likes: number;
  isFeatured: boolean;
  summary: string;
  date: string;
}

export const articles: Article[] = [
  {
    id: "KB-001",
    title: "Management of Severe Malaria in Nigerian Primary Health Centres",
    category: "Infectious Disease",
    author: "Dr. Ngozi Eze",
    authorTitle: "RN, MSc, Infectious Disease Specialist",
    evidenceLevel: "Level I",
    readTime: "12 min",
    likes: 234,
    isFeatured: true,
    summary: "A comprehensive guide on artesunate-based combination therapy protocols adapted for resource-limited settings in Nigeria.",
    date: "2024-03-10",
  },
  {
    id: "KB-002",
    title: "Lassa Fever: Early Detection and Infection Control for Frontline Nurses",
    category: "Infectious Disease",
    author: "Dr. Aminu Bello",
    authorTitle: "RN, PhD, Public Health Expert",
    evidenceLevel: "Level II",
    readTime: "15 min",
    likes: 189,
    isFeatured: true,
    summary: "Updated protocols for identifying Lassa fever symptoms and implementing barrier nursing techniques.",
    date: "2024-03-08",
  },
  {
    id: "KB-003",
    title: "Obstetric Emergency Response: Reducing Maternal Mortality",
    category: "Maternal Health",
    author: "Nurse Folake Williams",
    authorTitle: "RN, RM, MSc Midwifery",
    evidenceLevel: "Level I",
    readTime: "10 min",
    likes: 312,
    isFeatured: true,
    summary: "Evidence-based interventions for managing postpartum hemorrhage and eclampsia in Nigerian healthcare facilities.",
    date: "2024-03-05",
  },
  {
    id: "KB-004",
    title: "Pediatric Sickle Cell Disease: Pain Management Best Practices",
    category: "Pediatrics",
    author: "Nurse Chioma Nwosu",
    authorTitle: "RN, BSc, Pediatric Nurse Specialist",
    evidenceLevel: "Level II",
    readTime: "8 min",
    likes: 156,
    isFeatured: false,
    summary: "Practical approaches to pain assessment and management in children with sickle cell crisis.",
    date: "2024-03-02",
  },
  {
    id: "KB-005",
    title: "Trauma Assessment in Road Traffic Accidents: A Nigerian Context",
    category: "Emergency Care",
    author: "Nurse Emeka Okafor",
    authorTitle: "RN, Trauma & Emergency Specialist",
    evidenceLevel: "Level III",
    readTime: "14 min",
    likes: 198,
    isFeatured: false,
    summary: "Modified ATLS protocols adapted for Nigerian emergency departments with limited imaging resources.",
    date: "2024-02-28",
  },
  {
    id: "KB-006",
    title: "Antimicrobial Stewardship in Nigerian Hospitals",
    category: "Pharmacology",
    author: "Dr. Aisha Kano",
    authorTitle: "RN, PharmD, Clinical Pharmacist",
    evidenceLevel: "Level I",
    readTime: "11 min",
    likes: 145,
    isFeatured: false,
    summary: "Guidelines for rational antibiotic use to combat growing antimicrobial resistance in Nigerian healthcare settings.",
    date: "2024-02-25",
  },
  {
    id: "KB-007",
    title: "Community Health Nursing: Tackling Cholera Outbreaks",
    category: "Community Health",
    author: "Nurse Binta Mohammed",
    authorTitle: "RN, MPH, Community Health Nurse",
    evidenceLevel: "Level II",
    readTime: "9 min",
    likes: 167,
    isFeatured: false,
    summary: "Oral rehydration therapy deployment and community education strategies during cholera outbreaks.",
    date: "2024-02-20",
  },
  {
    id: "KB-008",
    title: "Neonatal Resuscitation: The First Golden Minute",
    category: "Emergency Care",
    author: "Nurse Halima Yusuf",
    authorTitle: "RN, Neonatal Intensive Care Specialist",
    evidenceLevel: "Level I",
    readTime: "7 min",
    likes: 278,
    isFeatured: true,
    summary: "Step-by-step guide to Helping Babies Breathe (HBB) protocol adapted for Nigerian delivery rooms.",
    date: "2024-02-18",
  },
  {
    id: "KB-009",
    title: "HIV/AIDS Care: From Testing to Treatment Adherence",
    category: "Infectious Disease",
    author: "Dr. Ngozi Eze",
    authorTitle: "RN, MSc, Infectious Disease Specialist",
    evidenceLevel: "Level I",
    readTime: "13 min",
    likes: 201,
    isFeatured: false,
    summary: "Comprehensive nursing care pathway for PMTCT and ART adherence support in Nigerian clinics.",
    date: "2024-02-15",
  },
];

export interface NurseProfile {
  id: string;
  name: string;
  initials: string;
  license: string;
  specialization: string;
  state: string;
  facility: string;
  rating: number;
  yearsExperience: number;
  availableForConsult: boolean;
  consultTypes: ("Video" | "Chat" | "Phone")[];
  languages: string[];
  expertise: string[];
}

export const nurseProfiles: NurseProfile[] = [
  {
    id: "N001",
    name: "Nurse Adaora Nwosu",
    initials: "AN",
    license: "RN-2019-4521",
    specialization: "Critical Care Nursing",
    state: "Lagos",
    facility: "Lagos University Teaching Hospital",
    rating: 4.9,
    yearsExperience: 8,
    availableForConsult: true,
    consultTypes: ["Video", "Chat"],
    languages: ["English", "Igbo", "Yoruba"],
    expertise: ["ICU Management", "Ventilator Care", "Sepsis Protocols"],
  },
  {
    id: "N002",
    name: "Nurse Adaeze Okonkwo",
    initials: "AO",
    license: "RN-2018-3892",
    specialization: "Emergency & Trauma",
    state: "Lagos",
    facility: "Lagos State General Hospital",
    rating: 4.7,
    yearsExperience: 6,
    availableForConsult: true,
    consultTypes: ["Video", "Phone"],
    languages: ["English", "Igbo"],
    expertise: ["Trauma Assessment", "Triage", "BLS/ACLS"],
  },
  {
    id: "N003",
    name: "Nurse Binta Mohammed",
    initials: "BM",
    license: "RN-2017-2847",
    specialization: "Community Health",
    state: "FCT",
    facility: "Garki Primary Health Centre",
    rating: 4.5,
    yearsExperience: 7,
    availableForConsult: true,
    consultTypes: ["Chat", "Phone"],
    languages: ["English", "Hausa", "Fulfulde"],
    expertise: ["Outbreak Response", "Immunization", "Health Education"],
  },
  {
    id: "N004",
    name: "Nurse Chioma Nwosu",
    initials: "CN",
    license: "RN-2020-5123",
    specialization: "Pediatric Nursing",
    state: "Enugu",
    facility: "University of Nigeria Teaching Hospital",
    rating: 4.8,
    yearsExperience: 4,
    availableForConsult: true,
    consultTypes: ["Video", "Chat", "Phone"],
    languages: ["English", "Igbo"],
    expertise: ["Neonatal Care", "Sickle Cell Management", "Child Development"],
  },
  {
    id: "N005",
    name: "Nurse Emeka Okafor",
    initials: "EO",
    license: "RN-2016-1934",
    specialization: "Trauma & Orthopedics",
    state: "Lagos",
    facility: "National Hospital, Abuja",
    rating: 4.6,
    yearsExperience: 9,
    availableForConsult: false,
    consultTypes: ["Video", "Phone"],
    languages: ["English", "Igbo", "Yoruba"],
    expertise: ["Fracture Management", "Wound Care", "Rehabilitation"],
  },
  {
    id: "N006",
    name: "Nurse Folake Williams",
    initials: "FW",
    license: "RM-2019-6721",
    specialization: "Midwifery",
    state: "Lagos",
    facility: "Lagos University Teaching Hospital",
    rating: 4.9,
    yearsExperience: 10,
    availableForConsult: true,
    consultTypes: ["Video", "Chat"],
    languages: ["English", "Yoruba"],
    expertise: ["High-Risk Pregnancy", "Postnatal Care", "Breastfeeding Support"],
  },
  {
    id: "N007",
    name: "Nurse Halima Yusuf",
    initials: "HY",
    license: "RN-2021-7432",
    specialization: "Neonatal Intensive Care",
    state: "Kaduna",
    facility: "Ahmadu Bello University Teaching Hospital",
    rating: 4.4,
    yearsExperience: 3,
    availableForConsult: true,
    consultTypes: ["Chat"],
    languages: ["English", "Hausa"],
    expertise: ["Neonatal Resuscitation", "Premature Care", "Kangaroo Care"],
  },
  {
    id: "N008",
    name: "Nurse Aisha Kano",
    initials: "AK",
    license: "RN-2015-1289",
    specialization: "Infectious Disease",
    state: "Kano",
    facility: "Federal Medical Centre, Abuja",
    rating: 4.7,
    yearsExperience: 11,
    availableForConsult: true,
    consultTypes: ["Video", "Chat", "Phone"],
    languages: ["English", "Hausa", "Arabic"],
    expertise: ["Lassa Fever Protocol", "HIV/AIDS Care", "Infection Control"],
  },
  {
    id: "N009",
    name: "Nurse Tunde Bakare",
    initials: "TB",
    license: "RN-2018-5567",
    specialization: "Oncology Nursing",
    state: "Lagos",
    facility: "Reddington Hospital",
    rating: 4.5,
    yearsExperience: 6,
    availableForConsult: false,
    consultTypes: ["Video"],
    languages: ["English", "Yoruba"],
    expertise: ["Chemotherapy Administration", "Palliative Care", "Patient Education"],
  },
];
