/**
 * Comprehensive Nigerian Healthcare Facilities Dataset
 * 161 facilities across all 36 states + FCT
 * Including: Teaching Hospitals, FMCs, PHCs, Private Hospitals,
 * University Health Centres, Specialist Centers, Maternity Homes,
 * Diagnostic Centers, Clinics, Rehabilitation Centers
 */

export interface FacilitySeedData {
  name: string
  type: string
  level: string
  address: string
  city: string
  state: string
  country: string
  latitude?: number
  longitude?: number
  phone?: string
  email?: string
  website?: string
  bedCapacity?: number
  staffCount?: number
  registrationNumber: string
  accreditingBody?: string
  accreditationStatus?: string
  isVerified: boolean
  isEmergencyCapable: boolean
  servicesOffered: string
  operatingHours?: string
}

export const NIGERIA_FACILITIES: FacilitySeedData[] = [
  // ===== FCT (Abuja) — 5 facilities =====
  {
    name: 'National Hospital Abuja', type: 'HOSPITAL', level: 'TERTIARY',
    address: 'Central District, Garki', city: 'Abuja', state: 'FCT', country: 'Nigeria',
    latitude: 9.0579, longitude: 7.4951, phone: '+234-9-523-3111', email: 'info@nationalhospital.gov.ng',
    website: 'https://nationalhospital.gov.ng', bedCapacity: 500, staffCount: 2100,
    registrationNumber: 'FHN/FCT/001', accreditingBody: 'Federal Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Emergency', 'Surgery', 'Pediatrics', 'Obstetrics', 'Neurosurgery', 'Nephrology', 'Cardiology', 'Orthopedics']),
    operatingHours: '24/7',
  },
  {
    name: 'Gwagwalada Primary Health Center', type: 'PRIMARY_HEALTH_CENTER', level: 'PRIMARY',
    address: 'Gwagwalada Town', city: 'Gwagwalada', state: 'FCT', country: 'Nigeria',
    phone: '+234-803-600-1234', bedCapacity: 30, staffCount: 45,
    registrationNumber: 'PHC/FCT/GWA/001', accreditingBody: 'FCT Primary Health Care Board',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: false,
    servicesOffered: JSON.stringify(['Antenatal Care', 'Immunization', 'Family Planning', 'Malaria Treatment', 'HIV Counseling']),
    operatingHours: 'Mon-Fri 8:00-17:00, Sat 8:00-13:00',
  },
  {
    name: 'Wuse General Hospital', type: 'HOSPITAL', level: 'SECONDARY',
    address: 'Wuse Zone 3', city: 'Abuja', state: 'FCT', country: 'Nigeria',
    latitude: 9.0610, longitude: 7.4740, phone: '+234-9-670-0456', bedCapacity: 200, staffCount: 650,
    registrationNumber: 'FHN/FCT/002', accreditingBody: 'FCT Health and Human Services Secretariat',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Emergency', 'General Surgery', 'Pediatrics', 'Obstetrics', 'Radiology', 'Laboratory']),
    operatingHours: '24/7',
  },
  {
    name: 'Maitama District Hospital', type: 'HOSPITAL', level: 'SECONDARY',
    address: 'Maitama District', city: 'Abuja', state: 'FCT', country: 'Nigeria',
    latitude: 9.0840, longitude: 7.4900, phone: '+234-9-413-2222', bedCapacity: 150, staffCount: 420,
    registrationNumber: 'FHN/FCT/003', accreditingBody: 'FCT Health and Human Services Secretariat',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Emergency', 'Surgery', 'Internal Medicine', 'Pediatrics', 'Obstetrics']),
    operatingHours: '24/7',
  },
  {
    name: 'Asokoro District Hospital', type: 'HOSPITAL', level: 'SECONDARY',
    address: 'Asokoro District', city: 'Abuja', state: 'FCT', country: 'Nigeria',
    latitude: 9.0360, longitude: 7.5040, phone: '+234-9-670-0500', bedCapacity: 120, staffCount: 350,
    registrationNumber: 'FHN/FCT/004', accreditingBody: 'FCT Health and Human Services Secretariat',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Emergency', 'Surgery', 'Pediatrics', 'Obstetrics', 'Laboratory']),
    operatingHours: '24/7',
  },

  // ===== Abia — 4 facilities =====
  {
    name: 'Federal Medical Centre Umuahia', type: 'HOSPITAL', level: 'TERTIARY',
    address: 'Azikiwe Road', city: 'Umuahia', state: 'Abia', country: 'Nigeria',
    latitude: 5.5300, longitude: 7.4890, phone: '+234-88-222-333', bedCapacity: 350, staffCount: 980,
    registrationNumber: 'FMC/ABIA/001', accreditingBody: 'Federal Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Emergency', 'Surgery', 'Pediatrics', 'Obstetrics', 'Internal Medicine', 'Radiology']),
    operatingHours: '24/7',
  },
  {
    name: 'Abia State University Teaching Hospital', type: 'HOSPITAL', level: 'TERTIARY',
    address: 'Aba-Owerri Road', city: 'Aba', state: 'Abia', country: 'Nigeria',
    latitude: 5.1070, longitude: 7.3560, phone: '+234-82-333-444', bedCapacity: 400, staffCount: 1200,
    registrationNumber: 'ABSUTH/ABIA/001', accreditingBody: 'Medical and Dental Council of Nigeria',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Emergency', 'Surgery', 'Pediatrics', 'Obstetrics', 'Orthopedics', 'Ophthalmology']),
    operatingHours: '24/7',
  },
  {
    name: 'Aba Primary Health Center', type: 'PRIMARY_HEALTH_CENTER', level: 'PRIMARY',
    address: 'Aba Town', city: 'Aba', state: 'Abia', country: 'Nigeria',
    phone: '+234-803-700-1001', bedCapacity: 25, staffCount: 35,
    registrationNumber: 'PHC/ABIA/ABA/001', accreditingBody: 'Abia State Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: false,
    servicesOffered: JSON.stringify(['Antenatal Care', 'Immunization', 'Family Planning', 'Malaria Treatment']),
    operatingHours: 'Mon-Fri 8:00-17:00',
  },
  {
    name: 'Ohafia Maternity Home', type: 'MATERNITY_HOME', level: 'PRIMARY',
    address: 'Ohafia Town', city: 'Ohafia', state: 'Abia', country: 'Nigeria',
    phone: '+234-803-700-1002', bedCapacity: 15, staffCount: 12,
    registrationNumber: 'MH/ABIA/OHA/001', accreditingBody: 'Abia State Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: false,
    servicesOffered: JSON.stringify(['Antenatal Care', 'Delivery', 'Postnatal Care', 'Family Planning']),
    operatingHours: 'Mon-Sat 8:00-18:00',
  },

  // ===== Adamawa — 4 facilities =====
  {
    name: 'Federal Medical Centre Yola', type: 'HOSPITAL', level: 'TERTIARY',
    address: 'Jimeta', city: 'Yola', state: 'Adamawa', country: 'Nigeria',
    latitude: 9.2035, longitude: 12.4950, phone: '+234-75-222-333', bedCapacity: 300, staffCount: 850,
    registrationNumber: 'FMC/ADAM/001', accreditingBody: 'Federal Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Emergency', 'Surgery', 'Pediatrics', 'Obstetrics', 'Internal Medicine', 'Radiology']),
    operatingHours: '24/7',
  },
  {
    name: 'Adamawa State Specialist Hospital', type: 'HOSPITAL', level: 'SECONDARY',
    address: 'Yola Town', city: 'Yola', state: 'Adamawa', country: 'Nigeria',
    phone: '+234-75-333-444', bedCapacity: 180, staffCount: 500,
    registrationNumber: 'ASH/ADAM/001', accreditingBody: 'Adamawa State Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Emergency', 'General Surgery', 'Pediatrics', 'Obstetrics']),
    operatingHours: '24/7',
  },
  {
    name: 'Mubi General Hospital', type: 'HOSPITAL', level: 'SECONDARY',
    address: 'Mubi Town', city: 'Mubi', state: 'Adamawa', country: 'Nigeria',
    phone: '+234-803-710-1001', bedCapacity: 100, staffCount: 280,
    registrationNumber: 'GH/ADAM/MUB/001', accreditingBody: 'Adamawa State Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Emergency', 'General Medicine', 'Surgery', 'Obstetrics']),
    operatingHours: '24/7',
  },
  {
    name: 'Ganye Primary Health Center', type: 'PRIMARY_HEALTH_CENTER', level: 'PRIMARY',
    address: 'Ganye Town', city: 'Ganye', state: 'Adamawa', country: 'Nigeria',
    phone: '+234-803-710-1002', bedCapacity: 20, staffCount: 30,
    registrationNumber: 'PHC/ADAM/GAN/001', accreditingBody: 'Adamawa State Primary Health Care Agency',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: false,
    servicesOffered: JSON.stringify(['Antenatal Care', 'Immunization', 'Malaria Treatment', 'Health Education']),
    operatingHours: 'Mon-Fri 8:00-17:00',
  },

  // ===== Akwa Ibom — 4 facilities =====
  {
    name: 'University of Uyo Teaching Hospital', type: 'HOSPITAL', level: 'TERTIARY',
    address: 'Use Offot', city: 'Uyo', state: 'Akwa Ibom', country: 'Nigeria',
    latitude: 5.0280, longitude: 7.8330, phone: '+234-85-222-333', bedCapacity: 450, staffCount: 1300,
    registrationNumber: 'UUTH/AK/001', accreditingBody: 'Federal Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Emergency', 'Surgery', 'Pediatrics', 'Obstetrics', 'Cardiology', 'Oncology', 'Radiology']),
    operatingHours: '24/7',
  },
  {
    name: 'Ibom Specialist Hospital', type: 'SPECIALIST_CENTER', level: 'TERTIARY',
    address: 'Oron Road', city: 'Uyo', state: 'Akwa Ibom', country: 'Nigeria',
    latitude: 5.0100, longitude: 7.8500, phone: '+234-85-333-444', bedCapacity: 200, staffCount: 600,
    registrationNumber: 'ISH/AK/001', accreditingBody: 'Akwa Ibom State Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Cardiology', 'Orthopedics', 'Oncology', 'Nephrology', 'Neurosurgery']),
    operatingHours: '24/7',
  },
  {
    name: 'Ikot Ekpene General Hospital', type: 'HOSPITAL', level: 'SECONDARY',
    address: 'Ikot Ekpene Town', city: 'Ikot Ekpene', state: 'Akwa Ibom', country: 'Nigeria',
    phone: '+234-803-720-1001', bedCapacity: 120, staffCount: 350,
    registrationNumber: 'GH/AK/IE/001', accreditingBody: 'Akwa Ibom State Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Emergency', 'General Surgery', 'Pediatrics', 'Obstetrics']),
    operatingHours: '24/7',
  },
  {
    name: 'Eket Primary Health Center', type: 'PRIMARY_HEALTH_CENTER', level: 'PRIMARY',
    address: 'Eket Town', city: 'Eket', state: 'Akwa Ibom', country: 'Nigeria',
    phone: '+234-803-720-1002', bedCapacity: 25, staffCount: 35,
    registrationNumber: 'PHC/AK/EKE/001', accreditingBody: 'Akwa Ibom State Primary Health Care Board',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: false,
    servicesOffered: JSON.stringify(['Antenatal Care', 'Immunization', 'Family Planning', 'Malaria Treatment']),
    operatingHours: 'Mon-Fri 8:00-17:00',
  },

  // ===== Anambra — 4 facilities =====
  {
    name: 'Chukwuemeka Odumegwu Ojukwu University Teaching Hospital', type: 'HOSPITAL', level: 'TERTIARY',
    address: 'Awka', city: 'Awka', state: 'Anambra', country: 'Nigeria',
    latitude: 6.2100, longitude: 7.0690, phone: '+234-803-730-0001', bedCapacity: 400, staffCount: 1100,
    registrationNumber: 'COOUTH/ANAM/001', accreditingBody: 'Medical and Dental Council of Nigeria',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Emergency', 'Surgery', 'Pediatrics', 'Obstetrics', 'Cardiology', 'Radiology', 'Laboratory']),
    operatingHours: '24/7',
  },
  {
    name: 'Onitsha General Hospital', type: 'HOSPITAL', level: 'SECONDARY',
    address: 'Onitsha', city: 'Onitsha', state: 'Anambra', country: 'Nigeria',
    latitude: 6.1450, longitude: 6.7890, phone: '+234-803-730-0002', bedCapacity: 180, staffCount: 520,
    registrationNumber: 'GH/ANAM/ONI/001', accreditingBody: 'Anambra State Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Emergency', 'General Surgery', 'Pediatrics', 'Obstetrics', 'Laboratory']),
    operatingHours: '24/7',
  },
  {
    name: 'Nnamdi Azikiwe University Teaching Hospital Nnewi', type: 'HOSPITAL', level: 'TERTIARY',
    address: 'Nnewi', city: 'Nnewi', state: 'Anambra', country: 'Nigeria',
    latitude: 5.9890, longitude: 6.9130, phone: '+234-803-730-0003', bedCapacity: 350, staffCount: 1000,
    registrationNumber: 'NAUTH/ANAM/001', accreditingBody: 'Federal Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Emergency', 'Surgery', 'Pediatrics', 'Obstetrics', 'Orthopedics', 'Ophthalmology']),
    operatingHours: '24/7',
  },
  {
    name: 'Awka Primary Health Center', type: 'PRIMARY_HEALTH_CENTER', level: 'PRIMARY',
    address: 'Awka Capital Territory', city: 'Awka', state: 'Anambra', country: 'Nigeria',
    phone: '+234-803-730-0004', bedCapacity: 30, staffCount: 40,
    registrationNumber: 'PHC/ANAM/AWK/001', accreditingBody: 'Anambra State Primary Health Care Agency',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: false,
    servicesOffered: JSON.stringify(['Antenatal Care', 'Immunization', 'Family Planning', 'Malaria Treatment', 'HIV Counseling']),
    operatingHours: 'Mon-Fri 8:00-17:00',
  },

  // ===== Bauchi — 4 facilities =====
  {
    name: 'Abubakar Tafawa Balewa University Teaching Hospital', type: 'HOSPITAL', level: 'TERTIARY',
    address: 'Bauchi', city: 'Bauchi', state: 'Bauchi', country: 'Nigeria',
    latitude: 10.3100, longitude: 9.8400, phone: '+234-77-222-333', bedCapacity: 400, staffCount: 1150,
    registrationNumber: 'ATBUTH/BAU/001', accreditingBody: 'Federal Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Emergency', 'Surgery', 'Pediatrics', 'Obstetrics', 'Internal Medicine', 'Radiology']),
    operatingHours: '24/7',
  },
  {
    name: 'Federal Medical Centre Azare', type: 'HOSPITAL', level: 'TERTIARY',
    address: 'Azare', city: 'Azare', state: 'Bauchi', country: 'Nigeria',
    phone: '+234-77-333-444', bedCapacity: 250, staffCount: 700,
    registrationNumber: 'FMC/BAU/AZA/001', accreditingBody: 'Federal Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Emergency', 'General Surgery', 'Pediatrics', 'Obstetrics']),
    operatingHours: '24/7',
  },
  {
    name: 'Bauchi State Specialist Hospital', type: 'HOSPITAL', level: 'SECONDARY',
    address: 'Bauchi Town', city: 'Bauchi', state: 'Bauchi', country: 'Nigeria',
    phone: '+234-803-740-1001', bedCapacity: 150, staffCount: 430,
    registrationNumber: 'SSH/BAU/001', accreditingBody: 'Bauchi State Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Emergency', 'Surgery', 'Pediatrics', 'Obstetrics']),
    operatingHours: '24/7',
  },
  {
    name: 'Misau Primary Health Center', type: 'PRIMARY_HEALTH_CENTER', level: 'PRIMARY',
    address: 'Misau Town', city: 'Misau', state: 'Bauchi', country: 'Nigeria',
    phone: '+234-803-740-1002', bedCapacity: 20, staffCount: 28,
    registrationNumber: 'PHC/BAU/MIS/001', accreditingBody: 'Bauchi State Primary Health Care Agency',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: false,
    servicesOffered: JSON.stringify(['Antenatal Care', 'Immunization', 'Malaria Treatment']),
    operatingHours: 'Mon-Fri 8:00-17:00',
  },

  // ===== Bayelsa — 4 facilities =====
  {
    name: 'Federal Medical Centre Yenagoa', type: 'HOSPITAL', level: 'TERTIARY',
    address: 'Yenagoa', city: 'Yenagoa', state: 'Bayelsa', country: 'Nigeria',
    latitude: 4.9240, longitude: 6.2650, phone: '+234-803-750-0001', bedCapacity: 280, staffCount: 800,
    registrationNumber: 'FMC/BAY/001', accreditingBody: 'Federal Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Emergency', 'Surgery', 'Pediatrics', 'Obstetrics', 'Internal Medicine']),
    operatingHours: '24/7',
  },
  {
    name: 'Niger Delta University Teaching Hospital', type: 'HOSPITAL', level: 'TERTIARY',
    address: 'Okolobiri', city: 'Yenagoa', state: 'Bayelsa', country: 'Nigeria',
    phone: '+234-803-750-0002', bedCapacity: 300, staffCount: 900,
    registrationNumber: 'NDUTH/BAY/001', accreditingBody: 'Federal Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Emergency', 'Surgery', 'Pediatrics', 'Obstetrics', 'Ophthalmology']),
    operatingHours: '24/7',
  },
  {
    name: 'Sagbama General Hospital', type: 'HOSPITAL', level: 'SECONDARY',
    address: 'Sagbama Town', city: 'Sagbama', state: 'Bayelsa', country: 'Nigeria',
    phone: '+234-803-750-0003', bedCapacity: 80, staffCount: 220,
    registrationNumber: 'GH/BAY/SAG/001', accreditingBody: 'Bayelsa State Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: false,
    servicesOffered: JSON.stringify(['General Medicine', 'Surgery', 'Obstetrics', 'Pediatrics']),
    operatingHours: '24/7',
  },
  {
    name: 'Ogbia Primary Health Center', type: 'PRIMARY_HEALTH_CENTER', level: 'PRIMARY',
    address: 'Ogbia Town', city: 'Ogbia', state: 'Bayelsa', country: 'Nigeria',
    phone: '+234-803-750-0004', bedCapacity: 15, staffCount: 20,
    registrationNumber: 'PHC/BAY/OGB/001', accreditingBody: 'Bayelsa State Primary Health Care Board',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: false,
    servicesOffered: JSON.stringify(['Antenatal Care', 'Immunization', 'Malaria Treatment']),
    operatingHours: 'Mon-Fri 8:00-17:00',
  },

  // ===== Benue — 4 facilities =====
  {
    name: 'Federal Medical Centre Makurdi', type: 'HOSPITAL', level: 'TERTIARY',
    address: 'Makurdi', city: 'Makurdi', state: 'Benue', country: 'Nigeria',
    latitude: 7.7310, longitude: 8.5390, phone: '+234-44-222-333', bedCapacity: 300, staffCount: 850,
    registrationNumber: 'FMC/BEN/001', accreditingBody: 'Federal Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Emergency', 'Surgery', 'Pediatrics', 'Obstetrics', 'Internal Medicine']),
    operatingHours: '24/7',
  },
  {
    name: 'Benue State University Teaching Hospital', type: 'HOSPITAL', level: 'TERTIARY',
    address: 'Makurdi', city: 'Makurdi', state: 'Benue', country: 'Nigeria',
    phone: '+234-44-333-444', bedCapacity: 250, staffCount: 750,
    registrationNumber: 'BSUTH/BEN/001', accreditingBody: 'Medical and Dental Council of Nigeria',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Emergency', 'Surgery', 'Pediatrics', 'Obstetrics', 'Radiology']),
    operatingHours: '24/7',
  },
  {
    name: 'Otukpo General Hospital', type: 'HOSPITAL', level: 'SECONDARY',
    address: 'Otukpo Town', city: 'Otukpo', state: 'Benue', country: 'Nigeria',
    phone: '+234-803-760-1001', bedCapacity: 100, staffCount: 300,
    registrationNumber: 'GH/BEN/OTU/001', accreditingBody: 'Benue State Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Emergency', 'General Surgery', 'Pediatrics', 'Obstetrics']),
    operatingHours: '24/7',
  },
  {
    name: 'Gboko Primary Health Center', type: 'PRIMARY_HEALTH_CENTER', level: 'PRIMARY',
    address: 'Gboko Town', city: 'Gboko', state: 'Benue', country: 'Nigeria',
    phone: '+234-803-760-1002', bedCapacity: 25, staffCount: 35,
    registrationNumber: 'PHC/BEN/GBK/001', accreditingBody: 'Benue State Primary Health Care Agency',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: false,
    servicesOffered: JSON.stringify(['Antenatal Care', 'Immunization', 'Malaria Treatment', 'Family Planning']),
    operatingHours: 'Mon-Fri 8:00-17:00',
  },

  // ===== Borno — 4 facilities =====
  {
    name: 'University of Maiduguri Teaching Hospital', type: 'HOSPITAL', level: 'TERTIARY',
    address: 'Baga Road', city: 'Maiduguri', state: 'Borno', country: 'Nigeria',
    latitude: 11.8310, longitude: 13.1510, phone: '+234-76-222-333', bedCapacity: 500, staffCount: 1400,
    registrationNumber: 'UMTH/BOR/001', accreditingBody: 'Federal Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Emergency', 'Surgery', 'Pediatrics', 'Obstetrics', 'Cardiology', 'Oncology', 'Trauma Care']),
    operatingHours: '24/7',
  },
  {
    name: 'Federal Medical Centre Nguru', type: 'HOSPITAL', level: 'TERTIARY',
    address: 'Nguru', city: 'Nguru', state: 'Borno', country: 'Nigeria',
    phone: '+234-76-333-444', bedCapacity: 200, staffCount: 600,
    registrationNumber: 'FMC/BOR/NGU/001', accreditingBody: 'Federal Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Emergency', 'General Surgery', 'Pediatrics', 'Obstetrics']),
    operatingHours: '24/7',
  },
  {
    name: 'State Specialist Hospital Maiduguri', type: 'HOSPITAL', level: 'SECONDARY',
    address: 'Maiduguri', city: 'Maiduguri', state: 'Borno', country: 'Nigeria',
    phone: '+234-803-770-1001', bedCapacity: 180, staffCount: 500,
    registrationNumber: 'SSH/BOR/001', accreditingBody: 'Borno State Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Emergency', 'General Medicine', 'Surgery', 'Pediatrics']),
    operatingHours: '24/7',
  },
  {
    name: 'Biu General Hospital', type: 'HOSPITAL', level: 'SECONDARY',
    address: 'Biu Town', city: 'Biu', state: 'Borno', country: 'Nigeria',
    phone: '+234-803-770-1002', bedCapacity: 80, staffCount: 230,
    registrationNumber: 'GH/BOR/BIU/001', accreditingBody: 'Borno State Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: false,
    servicesOffered: JSON.stringify(['General Medicine', 'Surgery', 'Obstetrics', 'Pediatrics']),
    operatingHours: '24/7',
  },

  // ===== Cross River — 4 facilities =====
  {
    name: 'University of Calabar Teaching Hospital', type: 'HOSPITAL', level: 'TERTIARY',
    address: 'Calabar', city: 'Calabar', state: 'Cross River', country: 'Nigeria',
    latitude: 4.9500, longitude: 8.3200, phone: '+234-87-222-333', bedCapacity: 450, staffCount: 1300,
    registrationNumber: 'UCTH/CR/001', accreditingBody: 'Federal Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Emergency', 'Surgery', 'Pediatrics', 'Obstetrics', 'Cardiology', 'Dermatology']),
    operatingHours: '24/7',
  },
  {
    name: 'General Hospital Calabar', type: 'HOSPITAL', level: 'SECONDARY',
    address: 'Calabar', city: 'Calabar', state: 'Cross River', country: 'Nigeria',
    phone: '+234-87-333-444', bedCapacity: 150, staffCount: 430,
    registrationNumber: 'GH/CR/CAL/001', accreditingBody: 'Cross River State Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Emergency', 'General Surgery', 'Pediatrics', 'Obstetrics']),
    operatingHours: '24/7',
  },
  {
    name: 'Ikom General Hospital', type: 'HOSPITAL', level: 'SECONDARY',
    address: 'Ikom Town', city: 'Ikom', state: 'Cross River', country: 'Nigeria',
    phone: '+234-803-780-1001', bedCapacity: 80, staffCount: 240,
    registrationNumber: 'GH/CR/IKO/001', accreditingBody: 'Cross River State Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: false,
    servicesOffered: JSON.stringify(['General Medicine', 'Surgery', 'Obstetrics', 'Pediatrics']),
    operatingHours: '24/7',
  },
  {
    name: 'Ogoja Primary Health Center', type: 'PRIMARY_HEALTH_CENTER', level: 'PRIMARY',
    address: 'Ogoja Town', city: 'Ogoja', state: 'Cross River', country: 'Nigeria',
    phone: '+234-803-780-1002', bedCapacity: 20, staffCount: 30,
    registrationNumber: 'PHC/CR/OGO/001', accreditingBody: 'Cross River State Primary Health Care Agency',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: false,
    servicesOffered: JSON.stringify(['Antenatal Care', 'Immunization', 'Malaria Treatment']),
    operatingHours: 'Mon-Fri 8:00-17:00',
  },

  // ===== Delta — 4 facilities =====
  {
    name: 'Federal Medical Centre Asaba', type: 'HOSPITAL', level: 'TERTIARY',
    address: 'Asaba', city: 'Asaba', state: 'Delta', country: 'Nigeria',
    latitude: 6.1960, longitude: 6.7170, phone: '+234-56-222-333', bedCapacity: 300, staffCount: 850,
    registrationNumber: 'FMC/DEL/001', accreditingBody: 'Federal Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Emergency', 'Surgery', 'Pediatrics', 'Obstetrics', 'Internal Medicine']),
    operatingHours: '24/7',
  },
  {
    name: 'Delta State University Teaching Hospital Oghara', type: 'HOSPITAL', level: 'TERTIARY',
    address: 'Oghara', city: 'Oghara', state: 'Delta', country: 'Nigeria',
    phone: '+234-56-333-444', bedCapacity: 350, staffCount: 1000,
    registrationNumber: 'DELSUTH/DEL/001', accreditingBody: 'Medical and Dental Council of Nigeria',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Emergency', 'Surgery', 'Pediatrics', 'Obstetrics', 'Orthopedics']),
    operatingHours: '24/7',
  },
  {
    name: 'Central Hospital Warri', type: 'HOSPITAL', level: 'SECONDARY',
    address: 'Warri', city: 'Warri', state: 'Delta', country: 'Nigeria',
    phone: '+234-803-790-1001', bedCapacity: 180, staffCount: 520,
    registrationNumber: 'GH/DEL/WAR/001', accreditingBody: 'Delta State Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Emergency', 'General Surgery', 'Pediatrics', 'Obstetrics']),
    operatingHours: '24/7',
  },
  {
    name: 'Sapele General Hospital', type: 'HOSPITAL', level: 'SECONDARY',
    address: 'Sapele', city: 'Sapele', state: 'Delta', country: 'Nigeria',
    phone: '+234-803-790-1002', bedCapacity: 100, staffCount: 290,
    registrationNumber: 'GH/DEL/SAP/001', accreditingBody: 'Delta State Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: false,
    servicesOffered: JSON.stringify(['General Medicine', 'Surgery', 'Obstetrics', 'Pediatrics']),
    operatingHours: '24/7',
  },

  // ===== Ebonyi — 4 facilities =====
  {
    name: 'Federal Teaching Hospital Abakaliki', type: 'HOSPITAL', level: 'TERTIARY',
    address: 'Abakaliki', city: 'Abakaliki', state: 'Ebonyi', country: 'Nigeria',
    latitude: 6.3100, longitude: 8.1100, phone: '+234-803-800-0001', bedCapacity: 350, staffCount: 1000,
    registrationNumber: 'FETHA/EBO/001', accreditingBody: 'Federal Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Emergency', 'Surgery', 'Pediatrics', 'Obstetrics', 'Internal Medicine', 'Nephrology']),
    operatingHours: '24/7',
  },
  {
    name: 'Ebonyi State University Teaching Hospital', type: 'HOSPITAL', level: 'TERTIARY',
    address: 'Abakaliki', city: 'Abakaliki', state: 'Ebonyi', country: 'Nigeria',
    phone: '+234-803-800-0002', bedCapacity: 250, staffCount: 750,
    registrationNumber: 'EBSUTH/EBO/001', accreditingBody: 'Medical and Dental Council of Nigeria',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Emergency', 'Surgery', 'Pediatrics', 'Obstetrics']),
    operatingHours: '24/7',
  },
  {
    name: 'Afikpo General Hospital', type: 'HOSPITAL', level: 'SECONDARY',
    address: 'Afikpo', city: 'Afikpo', state: 'Ebonyi', country: 'Nigeria',
    phone: '+234-803-800-0003', bedCapacity: 80, staffCount: 230,
    registrationNumber: 'GH/EBO/AFK/001', accreditingBody: 'Ebonyi State Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: false,
    servicesOffered: JSON.stringify(['General Medicine', 'Surgery', 'Obstetrics', 'Pediatrics']),
    operatingHours: '24/7',
  },
  {
    name: 'Onueke Primary Health Center', type: 'PRIMARY_HEALTH_CENTER', level: 'PRIMARY',
    address: 'Onueke', city: 'Onueke', state: 'Ebonyi', country: 'Nigeria',
    phone: '+234-803-800-0004', bedCapacity: 15, staffCount: 22,
    registrationNumber: 'PHC/EBO/ONU/001', accreditingBody: 'Ebonyi State Primary Health Care Agency',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: false,
    servicesOffered: JSON.stringify(['Antenatal Care', 'Immunization', 'Malaria Treatment']),
    operatingHours: 'Mon-Fri 8:00-17:00',
  },

  // ===== Edo — 4 facilities =====
  {
    name: 'University of Benin Teaching Hospital', type: 'HOSPITAL', level: 'TERTIARY',
    address: 'Ugbowo', city: 'Benin City', state: 'Edo', country: 'Nigeria',
    latitude: 6.3930, longitude: 5.6180, phone: '+234-52-222-333', bedCapacity: 550, staffCount: 1600,
    registrationNumber: 'UBTH/EDO/001', accreditingBody: 'Federal Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Emergency', 'Surgery', 'Pediatrics', 'Obstetrics', 'Cardiology', 'Oncology', 'Nephrology']),
    operatingHours: '24/7',
  },
  {
    name: 'Irrua Specialist Teaching Hospital', type: 'HOSPITAL', level: 'TERTIARY',
    address: 'Irrua', city: 'Irrua', state: 'Edo', country: 'Nigeria',
    phone: '+234-52-333-444', bedCapacity: 300, staffCount: 900,
    registrationNumber: 'ISTH/EDO/001', accreditingBody: 'Federal Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Emergency', 'Surgery', 'Pediatrics', 'Obstetrics', 'Lassa Fever Treatment', 'Infectious Diseases']),
    operatingHours: '24/7',
  },
  {
    name: 'Central Hospital Benin', type: 'HOSPITAL', level: 'SECONDARY',
    address: 'Benin City', city: 'Benin City', state: 'Edo', country: 'Nigeria',
    phone: '+234-803-810-1001', bedCapacity: 200, staffCount: 580,
    registrationNumber: 'GH/EDO/BEN/001', accreditingBody: 'Edo State Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Emergency', 'General Surgery', 'Pediatrics', 'Obstetrics']),
    operatingHours: '24/7',
  },
  {
    name: 'Auchi General Hospital', type: 'HOSPITAL', level: 'SECONDARY',
    address: 'Auchi', city: 'Auchi', state: 'Edo', country: 'Nigeria',
    phone: '+234-803-810-1002', bedCapacity: 100, staffCount: 300,
    registrationNumber: 'GH/EDO/AUC/001', accreditingBody: 'Edo State Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: false,
    servicesOffered: JSON.stringify(['General Medicine', 'Surgery', 'Obstetrics', 'Pediatrics']),
    operatingHours: '24/7',
  },

  // ===== Ekiti — 4 facilities =====
  {
    name: 'Federal Teaching Hospital Ido-Ekiti', type: 'HOSPITAL', level: 'TERTIARY',
    address: 'Ido-Ekiti', city: 'Ido-Ekiti', state: 'Ekiti', country: 'Nigeria',
    latitude: 7.8100, longitude: 5.2100, phone: '+234-803-820-0001', bedCapacity: 350, staffCount: 1000,
    registrationNumber: 'FETHI/EKI/001', accreditingBody: 'Federal Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Emergency', 'Surgery', 'Pediatrics', 'Obstetrics', 'Internal Medicine']),
    operatingHours: '24/7',
  },
  {
    name: 'Ekiti State University Teaching Hospital', type: 'HOSPITAL', level: 'TERTIARY',
    address: 'Ado-Ekiti', city: 'Ado-Ekiti', state: 'Ekiti', country: 'Nigeria',
    phone: '+234-803-820-0002', bedCapacity: 300, staffCount: 900,
    registrationNumber: 'EKSUTH/EKI/001', accreditingBody: 'Medical and Dental Council of Nigeria',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Emergency', 'Surgery', 'Pediatrics', 'Obstetrics', 'Radiology']),
    operatingHours: '24/7',
  },
  {
    name: 'Ado-Ekiti General Hospital', type: 'HOSPITAL', level: 'SECONDARY',
    address: 'Ado-Ekiti', city: 'Ado-Ekiti', state: 'Ekiti', country: 'Nigeria',
    phone: '+234-803-820-0003', bedCapacity: 120, staffCount: 350,
    registrationNumber: 'GH/EKI/ADO/001', accreditingBody: 'Ekiti State Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Emergency', 'General Surgery', 'Pediatrics', 'Obstetrics']),
    operatingHours: '24/7',
  },
  {
    name: 'Ikere-Ekiti Primary Health Center', type: 'PRIMARY_HEALTH_CENTER', level: 'PRIMARY',
    address: 'Ikere-Ekiti', city: 'Ikere-Ekiti', state: 'Ekiti', country: 'Nigeria',
    phone: '+234-803-820-0004', bedCapacity: 20, staffCount: 30,
    registrationNumber: 'PHC/EKI/IKR/001', accreditingBody: 'Ekiti State Primary Health Care Agency',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: false,
    servicesOffered: JSON.stringify(['Antenatal Care', 'Immunization', 'Malaria Treatment']),
    operatingHours: 'Mon-Fri 8:00-17:00',
  },

  // ===== Enugu — 4 facilities =====
  {
    name: 'University of Nigeria Teaching Hospital Ituku-Ozalla', type: 'HOSPITAL', level: 'TERTIARY',
    address: 'Ituku-Ozalla', city: 'Enugu', state: 'Enugu', country: 'Nigeria',
    latitude: 6.4400, longitude: 7.4900, phone: '+234-42-222-333', bedCapacity: 500, staffCount: 1500,
    registrationNumber: 'UNTH/ENU/001', accreditingBody: 'Federal Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Emergency', 'Surgery', 'Pediatrics', 'Obstetrics', 'Cardiology', 'Oncology', 'Orthopedics']),
    operatingHours: '24/7',
  },
  {
    name: 'Enugu State University Teaching Hospital', type: 'HOSPITAL', level: 'TERTIARY',
    address: 'Parklane', city: 'Enugu', state: 'Enugu', country: 'Nigeria',
    phone: '+234-42-333-444', bedCapacity: 300, staffCount: 900,
    registrationNumber: 'ESUTH/ENU/001', accreditingBody: 'Medical and Dental Council of Nigeria',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Emergency', 'Surgery', 'Pediatrics', 'Obstetrics', 'Radiology']),
    operatingHours: '24/7',
  },
  {
    name: 'National Orthopaedic Hospital Enugu', type: 'SPECIALIST_CENTER', level: 'TERTIARY',
    address: 'Enugu', city: 'Enugu', state: 'Enugu', country: 'Nigeria',
    phone: '+234-42-444-555', bedCapacity: 200, staffCount: 600,
    registrationNumber: 'NOHE/ENU/001', accreditingBody: 'Federal Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Orthopedics', 'Trauma Surgery', 'Physiotherapy', 'Rehabilitation']),
    operatingHours: '24/7',
  },
  {
    name: 'Nsukka General Hospital', type: 'HOSPITAL', level: 'SECONDARY',
    address: 'Nsukka', city: 'Nsukka', state: 'Enugu', country: 'Nigeria',
    phone: '+234-803-830-1001', bedCapacity: 100, staffCount: 290,
    registrationNumber: 'GH/ENU/NSU/001', accreditingBody: 'Enugu State Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: false,
    servicesOffered: JSON.stringify(['General Medicine', 'Surgery', 'Obstetrics', 'Pediatrics']),
    operatingHours: '24/7',
  },

  // ===== Gombe — 4 facilities =====
  {
    name: 'Federal Teaching Hospital Gombe', type: 'HOSPITAL', level: 'TERTIARY',
    address: 'Gombe', city: 'Gombe', state: 'Gombe', country: 'Nigeria',
    latitude: 10.2900, longitude: 11.1700, phone: '+234-72-222-333', bedCapacity: 350, staffCount: 1000,
    registrationNumber: 'FTHG/GOM/001', accreditingBody: 'Federal Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Emergency', 'Surgery', 'Pediatrics', 'Obstetrics', 'Internal Medicine']),
    operatingHours: '24/7',
  },
  {
    name: 'Gombe State Specialist Hospital', type: 'HOSPITAL', level: 'SECONDARY',
    address: 'Gombe Town', city: 'Gombe', state: 'Gombe', country: 'Nigeria',
    phone: '+234-72-333-444', bedCapacity: 150, staffCount: 430,
    registrationNumber: 'SSH/GOM/001', accreditingBody: 'Gombe State Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Emergency', 'General Surgery', 'Pediatrics', 'Obstetrics']),
    operatingHours: '24/7',
  },
  {
    name: 'Kaltungo General Hospital', type: 'HOSPITAL', level: 'SECONDARY',
    address: 'Kaltungo', city: 'Kaltungo', state: 'Gombe', country: 'Nigeria',
    phone: '+234-803-840-1001', bedCapacity: 80, staffCount: 220,
    registrationNumber: 'GH/GOM/KAL/001', accreditingBody: 'Gombe State Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: false,
    servicesOffered: JSON.stringify(['General Medicine', 'Surgery', 'Obstetrics']),
    operatingHours: '24/7',
  },
  {
    name: 'Dukku Primary Health Center', type: 'PRIMARY_HEALTH_CENTER', level: 'PRIMARY',
    address: 'Dukku', city: 'Dukku', state: 'Gombe', country: 'Nigeria',
    phone: '+234-803-840-1002', bedCapacity: 15, staffCount: 22,
    registrationNumber: 'PHC/GOM/DUK/001', accreditingBody: 'Gombe State Primary Health Care Agency',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: false,
    servicesOffered: JSON.stringify(['Antenatal Care', 'Immunization', 'Malaria Treatment']),
    operatingHours: 'Mon-Fri 8:00-17:00',
  },

  // ===== Imo — 4 facilities =====
  {
    name: 'Federal Medical Centre Owerri', type: 'HOSPITAL', level: 'TERTIARY',
    address: 'Owerri', city: 'Owerri', state: 'Imo', country: 'Nigeria',
    latitude: 5.4900, longitude: 7.0300, phone: '+234-83-222-333', bedCapacity: 350, staffCount: 1000,
    registrationNumber: 'FMC/IMO/001', accreditingBody: 'Federal Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Emergency', 'Surgery', 'Pediatrics', 'Obstetrics', 'Internal Medicine']),
    operatingHours: '24/7',
  },
  {
    name: 'Imo State University Teaching Hospital Orlu', type: 'HOSPITAL', level: 'TERTIARY',
    address: 'Orlu', city: 'Orlu', state: 'Imo', country: 'Nigeria',
    phone: '+234-83-333-444', bedCapacity: 280, staffCount: 800,
    registrationNumber: 'IMSUTH/IMO/001', accreditingBody: 'Medical and Dental Council of Nigeria',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Emergency', 'Surgery', 'Pediatrics', 'Obstetrics']),
    operatingHours: '24/7',
  },
  {
    name: 'General Hospital Okigwe', type: 'HOSPITAL', level: 'SECONDARY',
    address: 'Okigwe', city: 'Okigwe', state: 'Imo', country: 'Nigeria',
    phone: '+234-803-850-1001', bedCapacity: 100, staffCount: 300,
    registrationNumber: 'GH/IMO/OKI/001', accreditingBody: 'Imo State Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Emergency', 'General Surgery', 'Pediatrics', 'Obstetrics']),
    operatingHours: '24/7',
  },
  {
    name: 'Owerri Municipal Primary Health Center', type: 'PRIMARY_HEALTH_CENTER', level: 'PRIMARY',
    address: 'Owerri', city: 'Owerri', state: 'Imo', country: 'Nigeria',
    phone: '+234-803-850-1002', bedCapacity: 25, staffCount: 35,
    registrationNumber: 'PHC/IMO/OWE/001', accreditingBody: 'Imo State Primary Health Care Agency',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: false,
    servicesOffered: JSON.stringify(['Antenatal Care', 'Immunization', 'Malaria Treatment', 'Family Planning']),
    operatingHours: 'Mon-Fri 8:00-17:00',
  },

  // ===== Jigawa — 4 facilities =====
  {
    name: 'Federal Medical Centre Birnin Kudu', type: 'HOSPITAL', level: 'TERTIARY',
    address: 'Birnin Kudu', city: 'Birnin Kudu', state: 'Jigawa', country: 'Nigeria',
    latitude: 11.4500, longitude: 9.3800, phone: '+234-803-860-0001', bedCapacity: 250, staffCount: 700,
    registrationNumber: 'FMC/JIG/BK/001', accreditingBody: 'Federal Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Emergency', 'Surgery', 'Pediatrics', 'Obstetrics', 'Internal Medicine']),
    operatingHours: '24/7',
  },
  {
    name: 'Rasheed Shekoni Specialist Hospital Dutse', type: 'SPECIALIST_CENTER', level: 'TERTIARY',
    address: 'Dutse', city: 'Dutse', state: 'Jigawa', country: 'Nigeria',
    phone: '+234-803-860-0002', bedCapacity: 200, staffCount: 600,
    registrationNumber: 'RSSH/JIG/001', accreditingBody: 'Jigawa State Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Emergency', 'Surgery', 'Pediatrics', 'Obstetrics', 'Nephrology']),
    operatingHours: '24/7',
  },
  {
    name: 'Hadejia General Hospital', type: 'HOSPITAL', level: 'SECONDARY',
    address: 'Hadejia', city: 'Hadejia', state: 'Jigawa', country: 'Nigeria',
    phone: '+234-803-860-0003', bedCapacity: 100, staffCount: 280,
    registrationNumber: 'GH/JIG/HAD/001', accreditingBody: 'Jigawa State Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Emergency', 'General Medicine', 'Surgery', 'Obstetrics']),
    operatingHours: '24/7',
  },
  {
    name: 'Gumel Primary Health Center', type: 'PRIMARY_HEALTH_CENTER', level: 'PRIMARY',
    address: 'Gumel', city: 'Gumel', state: 'Jigawa', country: 'Nigeria',
    phone: '+234-803-860-0004', bedCapacity: 15, staffCount: 20,
    registrationNumber: 'PHC/JIG/GUM/001', accreditingBody: 'Jigawa State Primary Health Care Agency',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: false,
    servicesOffered: JSON.stringify(['Antenatal Care', 'Immunization', 'Malaria Treatment']),
    operatingHours: 'Mon-Fri 8:00-17:00',
  },

  // ===== Kaduna — 5 facilities =====
  {
    name: 'Ahmadu Bello University Teaching Hospital Zaria', type: 'HOSPITAL', level: 'TERTIARY',
    address: 'Shika-Zaria', city: 'Zaria', state: 'Kaduna', country: 'Nigeria',
    latitude: 11.1500, longitude: 7.6400, phone: '+234-69-222-333', bedCapacity: 500, staffCount: 1500,
    registrationNumber: 'ABUTH/KAD/001', accreditingBody: 'Federal Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Emergency', 'Surgery', 'Pediatrics', 'Obstetrics', 'Cardiology', 'Oncology', 'Radiology']),
    operatingHours: '24/7',
  },
  {
    name: 'National Eye Centre Kaduna', type: 'SPECIALIST_CENTER', level: 'TERTIARY',
    address: 'Kaduna', city: 'Kaduna', state: 'Kaduna', country: 'Nigeria',
    latitude: 10.5100, longitude: 7.4300, phone: '+234-62-222-333', bedCapacity: 150, staffCount: 450,
    registrationNumber: 'NEC/KAD/001', accreditingBody: 'Federal Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: false,
    servicesOffered: JSON.stringify(['Ophthalmology', 'Cataract Surgery', 'Glaucoma Treatment', 'Optometry']),
    operatingHours: 'Mon-Sat 8:00-18:00',
  },
  {
    name: 'Barau Dikko Specialist Hospital Kaduna', type: 'SPECIALIST_CENTER', level: 'SECONDARY',
    address: 'Kaduna', city: 'Kaduna', state: 'Kaduna', country: 'Nigeria',
    phone: '+234-62-333-444', bedCapacity: 200, staffCount: 580,
    registrationNumber: 'BDSH/KAD/001', accreditingBody: 'Kaduna State Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Emergency', 'Surgery', 'Pediatrics', 'Obstetrics', 'Internal Medicine']),
    operatingHours: '24/7',
  },
  {
    name: '44 Nigerian Army Reference Hospital Kaduna', type: 'HOSPITAL', level: 'SECONDARY',
    address: 'Kaduna', city: 'Kaduna', state: 'Kaduna', country: 'Nigeria',
    phone: '+234-62-444-555', bedCapacity: 250, staffCount: 700,
    registrationNumber: 'NARHK/KAD/001', accreditingBody: 'Nigerian Army Medical Corps',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Emergency', 'Surgery', 'Orthopedics', 'Physiotherapy', 'Trauma Care']),
    operatingHours: '24/7',
  },
  {
    name: 'Kafanchan General Hospital', type: 'HOSPITAL', level: 'SECONDARY',
    address: 'Kafanchan', city: 'Kafanchan', state: 'Kaduna', country: 'Nigeria',
    phone: '+234-803-870-1001', bedCapacity: 100, staffCount: 290,
    registrationNumber: 'GH/KAD/KAF/001', accreditingBody: 'Kaduna State Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: false,
    servicesOffered: JSON.stringify(['General Medicine', 'Surgery', 'Obstetrics', 'Pediatrics']),
    operatingHours: '24/7',
  },

  // ===== Kano — 5 facilities =====
  {
    name: 'Aminu Kano Teaching Hospital', type: 'HOSPITAL', level: 'TERTIARY',
    address: 'Zaria Road', city: 'Kano', state: 'Kano', country: 'Nigeria',
    latitude: 12.0000, longitude: 8.5300, phone: '+234-64-222-333', bedCapacity: 500, staffCount: 1500,
    registrationNumber: 'AKTH/KAN/001', accreditingBody: 'Federal Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Emergency', 'Surgery', 'Pediatrics', 'Obstetrics', 'Cardiology', 'Nephrology', 'Oncology']),
    operatingHours: '24/7',
  },
  {
    name: 'Murtala Muhammad Specialist Hospital Kano', type: 'HOSPITAL', level: 'SECONDARY',
    address: 'Kano City', city: 'Kano', state: 'Kano', country: 'Nigeria',
    phone: '+234-64-333-444', bedCapacity: 300, staffCount: 900,
    registrationNumber: 'MMSH/KAN/001', accreditingBody: 'Kano State Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Emergency', 'Surgery', 'Pediatrics', 'Obstetrics', 'Internal Medicine']),
    operatingHours: '24/7',
  },
  {
    name: 'Mohammed Abdullahi Wase Specialist Hospital Kano', type: 'SPECIALIST_CENTER', level: 'TERTIARY',
    address: 'Kano', city: 'Kano', state: 'Kano', country: 'Nigeria',
    phone: '+234-64-444-555', bedCapacity: 200, staffCount: 600,
    registrationNumber: 'MAWSH/KAN/001', accreditingBody: 'Kano State Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Orthopedics', 'Neurosurgery', 'Trauma Care', 'Spinal Surgery']),
    operatingHours: '24/7',
  },
  {
    name: 'Hasiya Bayero Pediatric Hospital Kano', type: 'SPECIALIST_CENTER', level: 'SECONDARY',
    address: 'Kano', city: 'Kano', state: 'Kano', country: 'Nigeria',
    phone: '+234-64-555-666', bedCapacity: 120, staffCount: 350,
    registrationNumber: 'HBPH/KAN/001', accreditingBody: 'Kano State Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Pediatric Care', 'Neonatal Intensive Care', 'Pediatric Surgery', 'Immunization']),
    operatingHours: '24/7',
  },
  {
    name: 'Wudil General Hospital', type: 'HOSPITAL', level: 'SECONDARY',
    address: 'Wudil', city: 'Wudil', state: 'Kano', country: 'Nigeria',
    phone: '+234-803-880-1001', bedCapacity: 80, staffCount: 230,
    registrationNumber: 'GH/KAN/WUD/001', accreditingBody: 'Kano State Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: false,
    servicesOffered: JSON.stringify(['General Medicine', 'Surgery', 'Obstetrics']),
    operatingHours: '24/7',
  },

  // ===== Katsina — 4 facilities =====
  {
    name: 'Federal Medical Centre Katsina', type: 'HOSPITAL', level: 'TERTIARY',
    address: 'Katsina', city: 'Katsina', state: 'Katsina', country: 'Nigeria',
    latitude: 12.9900, longitude: 7.6000, phone: '+234-65-222-333', bedCapacity: 300, staffCount: 850,
    registrationNumber: 'FMC/KAT/001', accreditingBody: 'Federal Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Emergency', 'Surgery', 'Pediatrics', 'Obstetrics', 'Internal Medicine']),
    operatingHours: '24/7',
  },
  {
    name: 'Katsina General Hospital', type: 'HOSPITAL', level: 'SECONDARY',
    address: 'Katsina Town', city: 'Katsina', state: 'Katsina', country: 'Nigeria',
    phone: '+234-65-333-444', bedCapacity: 180, staffCount: 520,
    registrationNumber: 'GH/KAT/001', accreditingBody: 'Katsina State Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Emergency', 'General Surgery', 'Pediatrics', 'Obstetrics']),
    operatingHours: '24/7',
  },
  {
    name: 'Funtua General Hospital', type: 'HOSPITAL', level: 'SECONDARY',
    address: 'Funtua', city: 'Funtua', state: 'Katsina', country: 'Nigeria',
    phone: '+234-803-890-1001', bedCapacity: 100, staffCount: 290,
    registrationNumber: 'GH/KAT/FUN/001', accreditingBody: 'Katsina State Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: false,
    servicesOffered: JSON.stringify(['General Medicine', 'Surgery', 'Obstetrics', 'Pediatrics']),
    operatingHours: '24/7',
  },
  {
    name: 'Daura Primary Health Center', type: 'PRIMARY_HEALTH_CENTER', level: 'PRIMARY',
    address: 'Daura', city: 'Daura', state: 'Katsina', country: 'Nigeria',
    phone: '+234-803-890-1002', bedCapacity: 15, staffCount: 20,
    registrationNumber: 'PHC/KAT/DAU/001', accreditingBody: 'Katsina State Primary Health Care Agency',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: false,
    servicesOffered: JSON.stringify(['Antenatal Care', 'Immunization', 'Malaria Treatment']),
    operatingHours: 'Mon-Fri 8:00-17:00',
  },

  // ===== Kebbi — 4 facilities =====
  {
    name: 'Federal Medical Centre Birnin Kebbi', type: 'HOSPITAL', level: 'TERTIARY',
    address: 'Birnin Kebbi', city: 'Birnin Kebbi', state: 'Kebbi', country: 'Nigeria',
    latitude: 12.4500, longitude: 4.2000, phone: '+234-803-900-0001', bedCapacity: 250, staffCount: 700,
    registrationNumber: 'FMC/KEB/001', accreditingBody: 'Federal Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Emergency', 'Surgery', 'Pediatrics', 'Obstetrics', 'Internal Medicine']),
    operatingHours: '24/7',
  },
  {
    name: 'Sir Yahaya Memorial Hospital Birnin Kebbi', type: 'HOSPITAL', level: 'SECONDARY',
    address: 'Birnin Kebbi', city: 'Birnin Kebbi', state: 'Kebbi', country: 'Nigeria',
    phone: '+234-803-900-0002', bedCapacity: 150, staffCount: 430,
    registrationNumber: 'SYMH/KEB/001', accreditingBody: 'Kebbi State Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Emergency', 'General Surgery', 'Pediatrics', 'Obstetrics']),
    operatingHours: '24/7',
  },
  {
    name: 'Argungu General Hospital', type: 'HOSPITAL', level: 'SECONDARY',
    address: 'Argungu', city: 'Argungu', state: 'Kebbi', country: 'Nigeria',
    phone: '+234-803-900-0003', bedCapacity: 80, staffCount: 230,
    registrationNumber: 'GH/KEB/ARG/001', accreditingBody: 'Kebbi State Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: false,
    servicesOffered: JSON.stringify(['General Medicine', 'Surgery', 'Obstetrics']),
    operatingHours: '24/7',
  },
  {
    name: 'Yauri Primary Health Center', type: 'PRIMARY_HEALTH_CENTER', level: 'PRIMARY',
    address: 'Yauri', city: 'Yauri', state: 'Kebbi', country: 'Nigeria',
    phone: '+234-803-900-0004', bedCapacity: 12, staffCount: 18,
    registrationNumber: 'PHC/KEB/YAU/001', accreditingBody: 'Kebbi State Primary Health Care Agency',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: false,
    servicesOffered: JSON.stringify(['Antenatal Care', 'Immunization', 'Malaria Treatment']),
    operatingHours: 'Mon-Fri 8:00-17:00',
  },

  // ===== Kogi — 4 facilities =====
  {
    name: 'Federal Medical Centre Lokoja', type: 'HOSPITAL', level: 'TERTIARY',
    address: 'Lokoja', city: 'Lokoja', state: 'Kogi', country: 'Nigeria',
    latitude: 7.8000, longitude: 6.7400, phone: '+234-803-910-0001', bedCapacity: 280, staffCount: 800,
    registrationNumber: 'FMC/KOG/001', accreditingBody: 'Federal Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Emergency', 'Surgery', 'Pediatrics', 'Obstetrics', 'Internal Medicine']),
    operatingHours: '24/7',
  },
  {
    name: 'Kogi State Specialist Hospital Lokoja', type: 'HOSPITAL', level: 'SECONDARY',
    address: 'Lokoja', city: 'Lokoja', state: 'Kogi', country: 'Nigeria',
    phone: '+234-803-910-0002', bedCapacity: 150, staffCount: 430,
    registrationNumber: 'KSSH/KOG/001', accreditingBody: 'Kogi State Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Emergency', 'General Surgery', 'Pediatrics', 'Obstetrics']),
    operatingHours: '24/7',
  },
  {
    name: 'Okene General Hospital', type: 'HOSPITAL', level: 'SECONDARY',
    address: 'Okene', city: 'Okene', state: 'Kogi', country: 'Nigeria',
    phone: '+234-803-910-0003', bedCapacity: 100, staffCount: 290,
    registrationNumber: 'GH/KOG/OKE/001', accreditingBody: 'Kogi State Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: false,
    servicesOffered: JSON.stringify(['General Medicine', 'Surgery', 'Obstetrics']),
    operatingHours: '24/7',
  },
  {
    name: 'Idah General Hospital', type: 'HOSPITAL', level: 'SECONDARY',
    address: 'Idah', city: 'Idah', state: 'Kogi', country: 'Nigeria',
    phone: '+234-803-910-0004', bedCapacity: 80, staffCount: 230,
    registrationNumber: 'GH/KOG/IDA/001', accreditingBody: 'Kogi State Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: false,
    servicesOffered: JSON.stringify(['General Medicine', 'Surgery', 'Obstetrics', 'Pediatrics']),
    operatingHours: '24/7',
  },

  // ===== Kwara — 4 facilities =====
  {
    name: 'University of Ilorin Teaching Hospital', type: 'HOSPITAL', level: 'TERTIARY',
    address: 'Oke-Ose', city: 'Ilorin', state: 'Kwara', country: 'Nigeria',
    latitude: 8.4800, longitude: 4.5400, phone: '+234-31-222-333', bedCapacity: 450, staffCount: 1300,
    registrationNumber: 'UITH/KWA/001', accreditingBody: 'Federal Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Emergency', 'Surgery', 'Pediatrics', 'Obstetrics', 'Cardiology', 'Oncology']),
    operatingHours: '24/7',
  },
  {
    name: 'General Hospital Ilorin', type: 'HOSPITAL', level: 'SECONDARY',
    address: 'Ilorin', city: 'Ilorin', state: 'Kwara', country: 'Nigeria',
    phone: '+234-31-333-444', bedCapacity: 200, staffCount: 580,
    registrationNumber: 'GH/KWA/ILR/001', accreditingBody: 'Kwara State Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Emergency', 'General Surgery', 'Pediatrics', 'Obstetrics']),
    operatingHours: '24/7',
  },
  {
    name: 'Offa General Hospital', type: 'HOSPITAL', level: 'SECONDARY',
    address: 'Offa', city: 'Offa', state: 'Kwara', country: 'Nigeria',
    phone: '+234-803-920-1001', bedCapacity: 100, staffCount: 290,
    registrationNumber: 'GH/KWA/OFF/001', accreditingBody: 'Kwara State Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: false,
    servicesOffered: JSON.stringify(['General Medicine', 'Surgery', 'Obstetrics']),
    operatingHours: '24/7',
  },
  {
    name: 'Jebba Primary Health Center', type: 'PRIMARY_HEALTH_CENTER', level: 'PRIMARY',
    address: 'Jebba', city: 'Jebba', state: 'Kwara', country: 'Nigeria',
    phone: '+234-803-920-1002', bedCapacity: 15, staffCount: 22,
    registrationNumber: 'PHC/KWA/JEB/001', accreditingBody: 'Kwara State Primary Health Care Agency',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: false,
    servicesOffered: JSON.stringify(['Antenatal Care', 'Immunization', 'Malaria Treatment']),
    operatingHours: 'Mon-Fri 8:00-17:00',
  },

  // ===== Lagos — 6 facilities =====
  {
    name: 'Lagos University Teaching Hospital', type: 'HOSPITAL', level: 'TERTIARY',
    address: 'Idi-Araba, Mushin', city: 'Lagos', state: 'Lagos', country: 'Nigeria',
    latitude: 6.5244, longitude: 3.3792, phone: '+234-1-497-2550', email: 'info@luth.org.ng',
    website: 'https://luth.org.ng', bedCapacity: 760, staffCount: 2850,
    registrationNumber: 'FHN/LAG/001', accreditingBody: 'Federal Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Emergency', 'Surgery', 'Pediatrics', 'Obstetrics', 'Cardiology', 'Oncology', 'Radiology', 'Laboratory']),
    operatingHours: '24/7',
  },
  {
    name: 'Lagos State University Teaching Hospital', type: 'HOSPITAL', level: 'TERTIARY',
    address: 'Ikeja', city: 'Lagos', state: 'Lagos', country: 'Nigeria',
    latitude: 6.5940, longitude: 3.3420, phone: '+234-1-794-1000', bedCapacity: 450, staffCount: 1400,
    registrationNumber: 'LASUTH/LAG/001', accreditingBody: 'Lagos State Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Emergency', 'Surgery', 'Pediatrics', 'Obstetrics', 'Orthopedics', 'Ophthalmology']),
    operatingHours: '24/7',
  },
  {
    name: 'Rainbow Specialist Medical Center', type: 'SPECIALIST_CENTER', level: 'SECONDARY',
    address: '52 Awolowo Road, Ikoyi', city: 'Lagos', state: 'Lagos', country: 'Nigeria',
    latitude: 6.4485, longitude: 3.4267, phone: '+234-1-269-7800', email: 'info@rainbowspecialist.com',
    bedCapacity: 80, staffCount: 180, registrationNumber: 'FHN/LAG/SPE/042',
    accreditingBody: 'Lagos State Ministry of Health', accreditationStatus: 'ACCREDITED',
    isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Cardiology', 'Endocrinology', 'Gastroenterology', 'Pulmonology', 'Rheumatology']),
    operatingHours: 'Mon-Sat 8:00-20:00, Emergency 24/7',
  },
  {
    name: 'Lagos Island Maternity Hospital', type: 'MATERNITY_HOME', level: 'SECONDARY',
    address: 'Lagos Island', city: 'Lagos', state: 'Lagos', country: 'Nigeria',
    latitude: 6.4500, longitude: 3.4000, phone: '+234-1-263-4567', bedCapacity: 100, staffCount: 280,
    registrationNumber: 'LIMH/LAG/001', accreditingBody: 'Lagos State Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Antenatal Care', 'Delivery', 'Postnatal Care', 'Neonatal Care', 'Emergency Obstetric Care']),
    operatingHours: '24/7',
  },
  {
    name: 'Alimosho General Hospital', type: 'HOSPITAL', level: 'SECONDARY',
    address: 'Igando', city: 'Lagos', state: 'Lagos', country: 'Nigeria',
    phone: '+234-1-897-6543', bedCapacity: 180, staffCount: 520,
    registrationNumber: 'GH/LAG/ALI/001', accreditingBody: 'Lagos State Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Emergency', 'General Surgery', 'Pediatrics', 'Obstetrics']),
    operatingHours: '24/7',
  },
  {
    name: 'Gbagada General Hospital', type: 'HOSPITAL', level: 'SECONDARY',
    address: 'Gbagada', city: 'Lagos', state: 'Lagos', country: 'Nigeria',
    phone: '+234-1-802-1234', bedCapacity: 150, staffCount: 430,
    registrationNumber: 'GH/LAG/GBA/001', accreditingBody: 'Lagos State Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Emergency', 'General Surgery', 'Pediatrics', 'Obstetrics', 'Radiology']),
    operatingHours: '24/7',
  },

  // ===== Nasarawa — 4 facilities =====
  {
    name: 'Federal Medical Centre Keffi', type: 'HOSPITAL', level: 'TERTIARY',
    address: 'Keffi', city: 'Keffi', state: 'Nasarawa', country: 'Nigeria',
    latitude: 8.8400, longitude: 7.8700, phone: '+234-803-930-0001', bedCapacity: 280, staffCount: 800,
    registrationNumber: 'FMC/NAS/KEF/001', accreditingBody: 'Federal Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Emergency', 'Surgery', 'Pediatrics', 'Obstetrics', 'Internal Medicine']),
    operatingHours: '24/7',
  },
  {
    name: 'Dalhatu Araf Specialist Hospital Lafia', type: 'HOSPITAL', level: 'TERTIARY',
    address: 'Lafia', city: 'Lafia', state: 'Nasarawa', country: 'Nigeria',
    phone: '+234-803-930-0002', bedCapacity: 250, staffCount: 720,
    registrationNumber: 'DASH/NAS/001', accreditingBody: 'Nasarawa State Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Emergency', 'Surgery', 'Pediatrics', 'Obstetrics']),
    operatingHours: '24/7',
  },
  {
    name: 'Akwanga General Hospital', type: 'HOSPITAL', level: 'SECONDARY',
    address: 'Akwanga', city: 'Akwanga', state: 'Nasarawa', country: 'Nigeria',
    phone: '+234-803-930-0003', bedCapacity: 80, staffCount: 230,
    registrationNumber: 'GH/NAS/AKW/001', accreditingBody: 'Nasarawa State Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: false,
    servicesOffered: JSON.stringify(['General Medicine', 'Surgery', 'Obstetrics']),
    operatingHours: '24/7',
  },
  {
    name: 'Lafia Primary Health Center', type: 'PRIMARY_HEALTH_CENTER', level: 'PRIMARY',
    address: 'Lafia', city: 'Lafia', state: 'Nasarawa', country: 'Nigeria',
    phone: '+234-803-930-0004', bedCapacity: 20, staffCount: 28,
    registrationNumber: 'PHC/NAS/LAF/001', accreditingBody: 'Nasarawa State Primary Health Care Agency',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: false,
    servicesOffered: JSON.stringify(['Antenatal Care', 'Immunization', 'Malaria Treatment']),
    operatingHours: 'Mon-Fri 8:00-17:00',
  },

  // ===== Niger — 4 facilities =====
  {
    name: 'Federal Medical Centre Bida', type: 'HOSPITAL', level: 'TERTIARY',
    address: 'Bida', city: 'Bida', state: 'Niger', country: 'Nigeria',
    latitude: 9.0800, longitude: 6.0100, phone: '+234-803-940-0001', bedCapacity: 300, staffCount: 850,
    registrationNumber: 'FMC/NIG/BID/001', accreditingBody: 'Federal Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Emergency', 'Surgery', 'Pediatrics', 'Obstetrics', 'Internal Medicine']),
    operatingHours: '24/7',
  },
  {
    name: 'Ibrahim Badamasi Babangida Specialist Hospital Minna', type: 'HOSPITAL', level: 'SECONDARY',
    address: 'Minna', city: 'Minna', state: 'Niger', country: 'Nigeria',
    phone: '+234-803-940-0002', bedCapacity: 200, staffCount: 580,
    registrationNumber: 'IBBSH/NIG/001', accreditingBody: 'Niger State Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Emergency', 'General Surgery', 'Pediatrics', 'Obstetrics']),
    operatingHours: '24/7',
  },
  {
    name: 'Suleja General Hospital', type: 'HOSPITAL', level: 'SECONDARY',
    address: 'Suleja', city: 'Suleja', state: 'Niger', country: 'Nigeria',
    phone: '+234-803-940-0003', bedCapacity: 100, staffCount: 290,
    registrationNumber: 'GH/NIG/SUL/001', accreditingBody: 'Niger State Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: false,
    servicesOffered: JSON.stringify(['General Medicine', 'Surgery', 'Obstetrics']),
    operatingHours: '24/7',
  },
  {
    name: 'Kontagora Primary Health Center', type: 'PRIMARY_HEALTH_CENTER', level: 'PRIMARY',
    address: 'Kontagora', city: 'Kontagora', state: 'Niger', country: 'Nigeria',
    phone: '+234-803-940-0004', bedCapacity: 18, staffCount: 25,
    registrationNumber: 'PHC/NIG/KON/001', accreditingBody: 'Niger State Primary Health Care Agency',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: false,
    servicesOffered: JSON.stringify(['Antenatal Care', 'Immunization', 'Malaria Treatment']),
    operatingHours: 'Mon-Fri 8:00-17:00',
  },

  // ===== Ogun — 4 facilities =====
  {
    name: 'Federal Medical Centre Abeokuta', type: 'HOSPITAL', level: 'TERTIARY',
    address: 'Abeokuta', city: 'Abeokuta', state: 'Ogun', country: 'Nigeria',
    latitude: 7.1500, longitude: 3.3500, phone: '+234-803-950-0001', bedCapacity: 300, staffCount: 850,
    registrationNumber: 'FMC/OGU/001', accreditingBody: 'Federal Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Emergency', 'Surgery', 'Pediatrics', 'Obstetrics', 'Internal Medicine']),
    operatingHours: '24/7',
  },
  {
    name: 'Olabisi Onabanjo University Teaching Hospital Sagamu', type: 'HOSPITAL', level: 'TERTIARY',
    address: 'Sagamu', city: 'Sagamu', state: 'Ogun', country: 'Nigeria',
    phone: '+234-803-950-0002', bedCapacity: 350, staffCount: 1000,
    registrationNumber: 'OOUTH/OGU/001', accreditingBody: 'Medical and Dental Council of Nigeria',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Emergency', 'Surgery', 'Pediatrics', 'Obstetrics', 'Radiology']),
    operatingHours: '24/7',
  },
  {
    name: 'Ijebu-Ode General Hospital', type: 'HOSPITAL', level: 'SECONDARY',
    address: 'Ijebu-Ode', city: 'Ijebu-Ode', state: 'Ogun', country: 'Nigeria',
    phone: '+234-803-950-0003', bedCapacity: 120, staffCount: 350,
    registrationNumber: 'GH/OGU/IOD/001', accreditingBody: 'Ogun State Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Emergency', 'General Surgery', 'Pediatrics', 'Obstetrics']),
    operatingHours: '24/7',
  },
  {
    name: 'Sango-Ota Primary Health Center', type: 'PRIMARY_HEALTH_CENTER', level: 'PRIMARY',
    address: 'Sango-Ota', city: 'Ota', state: 'Ogun', country: 'Nigeria',
    phone: '+234-803-950-0004', bedCapacity: 25, staffCount: 35,
    registrationNumber: 'PHC/OGU/SOT/001', accreditingBody: 'Ogun State Primary Health Care Board',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: false,
    servicesOffered: JSON.stringify(['Antenatal Care', 'Immunization', 'Malaria Treatment', 'Family Planning']),
    operatingHours: 'Mon-Fri 8:00-17:00',
  },

  // ===== Ondo — 4 facilities =====
  {
    name: 'Federal Medical Centre Owo', type: 'HOSPITAL', level: 'TERTIARY',
    address: 'Owo', city: 'Owo', state: 'Ondo', country: 'Nigeria',
    latitude: 7.1900, longitude: 5.5900, phone: '+234-803-960-0001', bedCapacity: 300, staffCount: 850,
    registrationNumber: 'FMC/OND/OWO/001', accreditingBody: 'Federal Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Emergency', 'Surgery', 'Pediatrics', 'Obstetrics', 'Internal Medicine']),
    operatingHours: '24/7',
  },
  {
    name: 'Ondo State University of Medical Sciences Teaching Hospital', type: 'HOSPITAL', level: 'TERTIARY',
    address: 'Ondo', city: 'Ondo', state: 'Ondo', country: 'Nigeria',
    phone: '+234-803-960-0002', bedCapacity: 280, staffCount: 800,
    registrationNumber: 'OSUMSTH/OND/001', accreditingBody: 'Ondo State Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Emergency', 'Surgery', 'Pediatrics', 'Obstetrics']),
    operatingHours: '24/7',
  },
  {
    name: 'Akure General Hospital', type: 'HOSPITAL', level: 'SECONDARY',
    address: 'Akure', city: 'Akure', state: 'Ondo', country: 'Nigeria',
    phone: '+234-803-960-0003', bedCapacity: 150, staffCount: 430,
    registrationNumber: 'GH/OND/AKU/001', accreditingBody: 'Ondo State Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Emergency', 'General Surgery', 'Pediatrics', 'Obstetrics']),
    operatingHours: '24/7',
  },
  {
    name: 'Okitipupa General Hospital', type: 'HOSPITAL', level: 'SECONDARY',
    address: 'Okitipupa', city: 'Okitipupa', state: 'Ondo', country: 'Nigeria',
    phone: '+234-803-960-0004', bedCapacity: 80, staffCount: 230,
    registrationNumber: 'GH/OND/OKI/001', accreditingBody: 'Ondo State Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: false,
    servicesOffered: JSON.stringify(['General Medicine', 'Surgery', 'Obstetrics']),
    operatingHours: '24/7',
  },

  // ===== Osun — 4 facilities =====
  {
    name: 'Obafemi Awolowo University Teaching Hospital Ile-Ife', type: 'HOSPITAL', level: 'TERTIARY',
    address: 'Ile-Ife', city: 'Ile-Ife', state: 'Osun', country: 'Nigeria',
    latitude: 7.5100, longitude: 4.5200, phone: '+234-803-970-0001', bedCapacity: 500, staffCount: 1500,
    registrationNumber: 'OAUTH/OSU/001', accreditingBody: 'Federal Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Emergency', 'Surgery', 'Pediatrics', 'Obstetrics', 'Cardiology', 'Oncology', 'Dermatology']),
    operatingHours: '24/7',
  },
  {
    name: 'Osun State University Teaching Hospital Osogbo', type: 'HOSPITAL', level: 'TERTIARY',
    address: 'Osogbo', city: 'Osogbo', state: 'Osun', country: 'Nigeria',
    phone: '+234-803-970-0002', bedCapacity: 280, staffCount: 800,
    registrationNumber: 'UNIOSUNTH/OSU/001', accreditingBody: 'Osun State Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Emergency', 'Surgery', 'Pediatrics', 'Obstetrics']),
    operatingHours: '24/7',
  },
  {
    name: 'Wesley Guild Hospital Ilesa', type: 'HOSPITAL', level: 'SECONDARY',
    address: 'Ilesa', city: 'Ilesa', state: 'Osun', country: 'Nigeria',
    phone: '+234-803-970-0003', bedCapacity: 200, staffCount: 580,
    registrationNumber: 'WGH/OSU/ILE/001', accreditingBody: 'Osun State Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Emergency', 'General Surgery', 'Pediatrics', 'Obstetrics']),
    operatingHours: '24/7',
  },
  {
    name: 'Ile-Ife Primary Health Center', type: 'PRIMARY_HEALTH_CENTER', level: 'PRIMARY',
    address: 'Ile-Ife', city: 'Ile-Ife', state: 'Osun', country: 'Nigeria',
    phone: '+234-803-970-0004', bedCapacity: 20, staffCount: 30,
    registrationNumber: 'PHC/OSU/IIF/001', accreditingBody: 'Osun State Primary Health Care Board',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: false,
    servicesOffered: JSON.stringify(['Antenatal Care', 'Immunization', 'Malaria Treatment']),
    operatingHours: 'Mon-Fri 8:00-17:00',
  },

  // ===== Oyo — 5 facilities =====
  {
    name: 'University College Hospital Ibadan', type: 'HOSPITAL', level: 'TERTIARY',
    address: 'Queen Elizabeth Road, Mokola', city: 'Ibadan', state: 'Oyo', country: 'Nigeria',
    latitude: 7.3775, longitude: 3.9470, phone: '+234-2-241-0088', email: 'info@uch-ibadan.org.ng',
    bedCapacity: 650, staffCount: 2400, registrationNumber: 'FHN/OYO/001',
    accreditingBody: 'Federal Ministry of Health', accreditationStatus: 'ACCREDITED',
    isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Emergency', 'Surgery', 'Pediatrics', 'Obstetrics', 'Oncology', 'Dermatology', 'Psychiatry', 'Radiology']),
    operatingHours: '24/7',
  },
  {
    name: 'Ladoke Akintola University of Technology Teaching Hospital Ogbomoso', type: 'HOSPITAL', level: 'TERTIARY',
    address: 'Ogbomoso', city: 'Ogbomoso', state: 'Oyo', country: 'Nigeria',
    phone: '+234-803-980-0002', bedCapacity: 300, staffCount: 900,
    registrationNumber: 'LAUTECHTH/OYO/001', accreditingBody: 'Oyo State Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Emergency', 'Surgery', 'Pediatrics', 'Obstetrics']),
    operatingHours: '24/7',
  },
  {
    name: 'Adeoyo Maternity Hospital Ibadan', type: 'MATERNITY_HOME', level: 'SECONDARY',
    address: 'Yemetu', city: 'Ibadan', state: 'Oyo', country: 'Nigeria',
    phone: '+234-803-980-0003', bedCapacity: 150, staffCount: 420,
    registrationNumber: 'AMH/OYO/001', accreditingBody: 'Oyo State Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Antenatal Care', 'Delivery', 'Postnatal Care', 'Neonatal Care']),
    operatingHours: '24/7',
  },
  {
    name: 'Ring Road State Hospital Ibadan', type: 'HOSPITAL', level: 'SECONDARY',
    address: 'Ring Road', city: 'Ibadan', state: 'Oyo', country: 'Nigeria',
    phone: '+234-803-980-0004', bedCapacity: 180, staffCount: 520,
    registrationNumber: 'RRSH/OYO/001', accreditingBody: 'Oyo State Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Emergency', 'General Surgery', 'Pediatrics', 'Obstetrics']),
    operatingHours: '24/7',
  },
  {
    name: 'Iseyin General Hospital', type: 'HOSPITAL', level: 'SECONDARY',
    address: 'Iseyin', city: 'Iseyin', state: 'Oyo', country: 'Nigeria',
    phone: '+234-803-980-0005', bedCapacity: 80, staffCount: 230,
    registrationNumber: 'GH/OYO/ISE/001', accreditingBody: 'Oyo State Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: false,
    servicesOffered: JSON.stringify(['General Medicine', 'Surgery', 'Obstetrics']),
    operatingHours: '24/7',
  },

  // ===== Plateau — 4 facilities =====
  {
    name: 'Jos University Teaching Hospital', type: 'HOSPITAL', level: 'TERTIARY',
    address: 'Jos', city: 'Jos', state: 'Plateau', country: 'Nigeria',
    latitude: 9.8960, longitude: 8.8580, phone: '+234-73-222-333', bedCapacity: 450, staffCount: 1300,
    registrationNumber: 'JUTH/PLA/001', accreditingBody: 'Federal Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Emergency', 'Surgery', 'Pediatrics', 'Obstetrics', 'Oncology', 'Dermatology']),
    operatingHours: '24/7',
  },
  {
    name: 'Plateau State Specialist Hospital Jos', type: 'HOSPITAL', level: 'SECONDARY',
    address: 'Jos', city: 'Jos', state: 'Plateau', country: 'Nigeria',
    phone: '+234-73-333-444', bedCapacity: 200, staffCount: 580,
    registrationNumber: 'PSSH/PLA/001', accreditingBody: 'Plateau State Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Emergency', 'General Surgery', 'Pediatrics', 'Obstetrics']),
    operatingHours: '24/7',
  },
  {
    name: 'Bokkos General Hospital', type: 'HOSPITAL', level: 'SECONDARY',
    address: 'Bokkos', city: 'Bokkos', state: 'Plateau', country: 'Nigeria',
    phone: '+234-803-990-1001', bedCapacity: 60, staffCount: 170,
    registrationNumber: 'GH/PLA/BOK/001', accreditingBody: 'Plateau State Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: false,
    servicesOffered: JSON.stringify(['General Medicine', 'Surgery', 'Obstetrics']),
    operatingHours: '24/7',
  },
  {
    name: 'Pankshin Primary Health Center', type: 'PRIMARY_HEALTH_CENTER', level: 'PRIMARY',
    address: 'Pankshin', city: 'Pankshin', state: 'Plateau', country: 'Nigeria',
    phone: '+234-803-990-1002', bedCapacity: 15, staffCount: 22,
    registrationNumber: 'PHC/PLA/PAN/001', accreditingBody: 'Plateau State Primary Health Care Agency',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: false,
    servicesOffered: JSON.stringify(['Antenatal Care', 'Immunization', 'Malaria Treatment']),
    operatingHours: 'Mon-Fri 8:00-17:00',
  },

  // ===== Rivers — 5 facilities =====
  {
    name: 'University of Port Harcourt Teaching Hospital', type: 'HOSPITAL', level: 'TERTIARY',
    address: 'Choba', city: 'Port Harcourt', state: 'Rivers', country: 'Nigeria',
    latitude: 4.8900, longitude: 6.8900, phone: '+234-84-222-333', bedCapacity: 500, staffCount: 1500,
    registrationNumber: 'UPTH/RIV/001', accreditingBody: 'Federal Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Emergency', 'Surgery', 'Pediatrics', 'Obstetrics', 'Cardiology', 'Nephrology', 'Oncology']),
    operatingHours: '24/7',
  },
  {
    name: 'Rivers State University Teaching Hospital', type: 'HOSPITAL', level: 'TERTIARY',
    address: 'Port Harcourt', city: 'Port Harcourt', state: 'Rivers', country: 'Nigeria',
    phone: '+234-84-333-444', bedCapacity: 350, staffCount: 1000,
    registrationNumber: 'RSUTH/RIV/001', accreditingBody: 'Rivers State Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Emergency', 'Surgery', 'Pediatrics', 'Obstetrics']),
    operatingHours: '24/7',
  },
  {
    name: 'Braithwaite Memorial Specialist Hospital Port Harcourt', type: 'SPECIALIST_CENTER', level: 'TERTIARY',
    address: 'Port Harcourt', city: 'Port Harcourt', state: 'Rivers', country: 'Nigeria',
    phone: '+234-84-444-555', bedCapacity: 250, staffCount: 720,
    registrationNumber: 'BMSH/RIV/001', accreditingBody: 'Rivers State Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Orthopedics', 'Oncology', 'Neurosurgery', 'Cardiology']),
    operatingHours: '24/7',
  },
  {
    name: 'Eleme General Hospital', type: 'HOSPITAL', level: 'SECONDARY',
    address: 'Eleme', city: 'Eleme', state: 'Rivers', country: 'Nigeria',
    phone: '+234-84-555-666', bedCapacity: 100, staffCount: 290,
    registrationNumber: 'GH/RIV/ELE/001', accreditingBody: 'Rivers State Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: false,
    servicesOffered: JSON.stringify(['General Medicine', 'Surgery', 'Obstetrics']),
    operatingHours: '24/7',
  },
  {
    name: 'Bonny Primary Health Center', type: 'PRIMARY_HEALTH_CENTER', level: 'PRIMARY',
    address: 'Bonny Island', city: 'Bonny', state: 'Rivers', country: 'Nigeria',
    phone: '+234-804-000-1001', bedCapacity: 20, staffCount: 30,
    registrationNumber: 'PHC/RIV/BON/001', accreditingBody: 'Rivers State Primary Health Care Board',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: false,
    servicesOffered: JSON.stringify(['Antenatal Care', 'Immunization', 'Malaria Treatment', 'HIV Counseling']),
    operatingHours: 'Mon-Fri 8:00-17:00',
  },

  // ===== Sokoto — 4 facilities =====
  {
    name: 'Usmanu Danfodiyo University Teaching Hospital Sokoto', type: 'HOSPITAL', level: 'TERTIARY',
    address: 'Sokoto', city: 'Sokoto', state: 'Sokoto', country: 'Nigeria',
    latitude: 13.0600, longitude: 5.2300, phone: '+234-60-222-333', bedCapacity: 450, staffCount: 1300,
    registrationNumber: 'UDUTH/SOK/001', accreditingBody: 'Federal Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Emergency', 'Surgery', 'Pediatrics', 'Obstetrics', 'Oncology', 'Radiology']),
    operatingHours: '24/7',
  },
  {
    name: 'Sokoto Specialist Hospital', type: 'HOSPITAL', level: 'SECONDARY',
    address: 'Sokoto', city: 'Sokoto', state: 'Sokoto', country: 'Nigeria',
    phone: '+234-60-333-444', bedCapacity: 180, staffCount: 520,
    registrationNumber: 'SSH/SOK/001', accreditingBody: 'Sokoto State Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Emergency', 'General Surgery', 'Pediatrics', 'Obstetrics']),
    operatingHours: '24/7',
  },
  {
    name: 'Wamakko General Hospital', type: 'HOSPITAL', level: 'SECONDARY',
    address: 'Wamakko', city: 'Wamakko', state: 'Sokoto', country: 'Nigeria',
    phone: '+234-804-010-1001', bedCapacity: 80, staffCount: 230,
    registrationNumber: 'GH/SOK/WAM/001', accreditingBody: 'Sokoto State Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: false,
    servicesOffered: JSON.stringify(['General Medicine', 'Surgery', 'Obstetrics']),
    operatingHours: '24/7',
  },
  {
    name: 'Gwadabawa Primary Health Center', type: 'PRIMARY_HEALTH_CENTER', level: 'PRIMARY',
    address: 'Gwadabawa', city: 'Gwadabawa', state: 'Sokoto', country: 'Nigeria',
    phone: '+234-804-010-1002', bedCapacity: 12, staffCount: 18,
    registrationNumber: 'PHC/SOK/GWA/001', accreditingBody: 'Sokoto State Primary Health Care Agency',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: false,
    servicesOffered: JSON.stringify(['Antenatal Care', 'Immunization', 'Malaria Treatment']),
    operatingHours: 'Mon-Fri 8:00-17:00',
  },

  // ===== Taraba — 4 facilities =====
  {
    name: 'Federal Medical Centre Jalingo', type: 'HOSPITAL', level: 'TERTIARY',
    address: 'Jalingo', city: 'Jalingo', state: 'Taraba', country: 'Nigeria',
    latitude: 8.8900, longitude: 11.3600, phone: '+234-804-020-0001', bedCapacity: 250, staffCount: 700,
    registrationNumber: 'FMC/TAR/JAL/001', accreditingBody: 'Federal Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Emergency', 'Surgery', 'Pediatrics', 'Obstetrics', 'Internal Medicine']),
    operatingHours: '24/7',
  },
  {
    name: 'Taraba State Specialist Hospital Jalingo', type: 'HOSPITAL', level: 'SECONDARY',
    address: 'Jalingo', city: 'Jalingo', state: 'Taraba', country: 'Nigeria',
    phone: '+234-804-020-0002', bedCapacity: 150, staffCount: 430,
    registrationNumber: 'TSSH/TAR/001', accreditingBody: 'Taraba State Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Emergency', 'General Surgery', 'Pediatrics', 'Obstetrics']),
    operatingHours: '24/7',
  },
  {
    name: 'Wukari General Hospital', type: 'HOSPITAL', level: 'SECONDARY',
    address: 'Wukari', city: 'Wukari', state: 'Taraba', country: 'Nigeria',
    phone: '+234-804-020-0003', bedCapacity: 80, staffCount: 230,
    registrationNumber: 'GH/TAR/WUK/001', accreditingBody: 'Taraba State Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: false,
    servicesOffered: JSON.stringify(['General Medicine', 'Surgery', 'Obstetrics']),
    operatingHours: '24/7',
  },
  {
    name: 'Gembu Primary Health Center', type: 'PRIMARY_HEALTH_CENTER', level: 'PRIMARY',
    address: 'Gembu', city: 'Gembu', state: 'Taraba', country: 'Nigeria',
    phone: '+234-804-020-0004', bedCapacity: 10, staffCount: 15,
    registrationNumber: 'PHC/TAR/GEM/001', accreditingBody: 'Taraba State Primary Health Care Agency',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: false,
    servicesOffered: JSON.stringify(['Antenatal Care', 'Immunization', 'Malaria Treatment']),
    operatingHours: 'Mon-Fri 8:00-17:00',
  },

  // ===== Yobe — 4 facilities =====
  {
    name: 'Federal Medical Centre Nguru', type: 'HOSPITAL', level: 'TERTIARY',
    address: 'Nguru', city: 'Nguru', state: 'Yobe', country: 'Nigeria',
    latitude: 12.8700, longitude: 10.4600, phone: '+234-804-030-0001', bedCapacity: 200, staffCount: 580,
    registrationNumber: 'FMC/YOB/NGU/001', accreditingBody: 'Federal Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Emergency', 'Surgery', 'Pediatrics', 'Obstetrics', 'Internal Medicine']),
    operatingHours: '24/7',
  },
  {
    name: 'Yobe State University Teaching Hospital Damaturu', type: 'HOSPITAL', level: 'TERTIARY',
    address: 'Damaturu', city: 'Damaturu', state: 'Yobe', country: 'Nigeria',
    phone: '+234-804-030-0002', bedCapacity: 250, staffCount: 720,
    registrationNumber: 'YSUTH/YOB/001', accreditingBody: 'Yobe State Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Emergency', 'Surgery', 'Pediatrics', 'Obstetrics']),
    operatingHours: '24/7',
  },
  {
    name: 'Potiskum General Hospital', type: 'HOSPITAL', level: 'SECONDARY',
    address: 'Potiskum', city: 'Potiskum', state: 'Yobe', country: 'Nigeria',
    phone: '+234-804-030-0003', bedCapacity: 100, staffCount: 290,
    registrationNumber: 'GH/YOB/POT/001', accreditingBody: 'Yobe State Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: false,
    servicesOffered: JSON.stringify(['General Medicine', 'Surgery', 'Obstetrics']),
    operatingHours: '24/7',
  },
  {
    name: 'Geidam Primary Health Center', type: 'PRIMARY_HEALTH_CENTER', level: 'PRIMARY',
    address: 'Geidam', city: 'Geidam', state: 'Yobe', country: 'Nigeria',
    phone: '+234-804-030-0004', bedCapacity: 12, staffCount: 18,
    registrationNumber: 'PHC/YOB/GEI/001', accreditingBody: 'Yobe State Primary Health Care Agency',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: false,
    servicesOffered: JSON.stringify(['Antenatal Care', 'Immunization', 'Malaria Treatment']),
    operatingHours: 'Mon-Fri 8:00-17:00',
  },

  // ===== Zamfara — 4 facilities =====
  {
    name: 'Federal Medical Centre Gusau', type: 'HOSPITAL', level: 'TERTIARY',
    address: 'Gusau', city: 'Gusau', state: 'Zamfara', country: 'Nigeria',
    latitude: 12.1700, longitude: 6.6600, phone: '+234-804-040-0001', bedCapacity: 250, staffCount: 700,
    registrationNumber: 'FMC/ZAM/GUS/001', accreditingBody: 'Federal Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Emergency', 'Surgery', 'Pediatrics', 'Obstetrics', 'Internal Medicine']),
    operatingHours: '24/7',
  },
  {
    name: 'Yusuf Dantsoho Memorial Hospital Gusau', type: 'HOSPITAL', level: 'SECONDARY',
    address: 'Gusau', city: 'Gusau', state: 'Zamfara', country: 'Nigeria',
    phone: '+234-804-040-0002', bedCapacity: 150, staffCount: 430,
    registrationNumber: 'YDMH/ZAM/001', accreditingBody: 'Zamfara State Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: true,
    servicesOffered: JSON.stringify(['Emergency', 'General Surgery', 'Pediatrics', 'Obstetrics']),
    operatingHours: '24/7',
  },
  {
    name: 'Kaura Namoda General Hospital', type: 'HOSPITAL', level: 'SECONDARY',
    address: 'Kaura Namoda', city: 'Kaura Namoda', state: 'Zamfara', country: 'Nigeria',
    phone: '+234-804-040-0003', bedCapacity: 80, staffCount: 230,
    registrationNumber: 'GH/ZAM/KN/001', accreditingBody: 'Zamfara State Ministry of Health',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: false,
    servicesOffered: JSON.stringify(['General Medicine', 'Surgery', 'Obstetrics']),
    operatingHours: '24/7',
  },
  {
    name: 'Talata Mafara Primary Health Center', type: 'PRIMARY_HEALTH_CENTER', level: 'PRIMARY',
    address: 'Talata Mafara', city: 'Talata Mafara', state: 'Zamfara', country: 'Nigeria',
    phone: '+234-804-040-0004', bedCapacity: 15, staffCount: 22,
    registrationNumber: 'PHC/ZAM/TM/001', accreditingBody: 'Zamfara State Primary Health Care Agency',
    accreditationStatus: 'ACCREDITED', isVerified: true, isEmergencyCapable: false,
    servicesOffered: JSON.stringify(['Antenatal Care', 'Immunization', 'Malaria Treatment']),
    operatingHours: 'Mon-Fri 8:00-17:00',
  },
]
