// NurseID Module - Shared Data

export const nurseProfile = {
  firstName: "Adaora",
  lastName: "Nwosu",
  fullName: "Adaora Nwosu",
  title: "Registered Nurse",
  licenseNumber: "NMCN/RN/2021/08754",
  specialization: "Emergency & Critical Care Nursing",
  email: "adaora.nwosu@lagosteachinghospital.ng",
  phone: "+234 803 456 7890",
  address: "14 Admiralty Way, Lekki Phase 1, Lagos",
  state: "Lagos State",
  country: "Nigeria",
  dateOfBirth: "1992-03-15",
  gender: "Female",
  avatar: "",
  initials: "AN",
  bio: "Dedicated and compassionate Registered Nurse with 8+ years of experience in emergency and critical care nursing at Lagos University Teaching Hospital (LUTH). Passionate about improving patient outcomes through evidence-based practice and continuous professional development. Certified in BLS, ACLS, and trauma nursing with expertise in managing complex clinical scenarios in resource-limited settings.",
  skills: [
    "Emergency Triage",
    "Critical Care",
    "IV Therapy",
    "Wound Management",
    "Patient Assessment",
    "Trauma Nursing",
    "Ventilator Management",
    "Infection Control",
    "Patient Education",
    "EHR Documentation",
  ],
  languages: ["English", "Yoruba", "Igbo"],
  rating: 4.8,
  reviewCount: 127,
  yearsExperience: 8,
  facility: "Lagos University Teaching Hospital",
  ward: "Emergency Department",
  availableForConsultation: true,
  profileCompletion: 85,
  joinDate: "2021-06-15",
};

export const credentials = [
  {
    id: "cred-1",
    name: "Nursing & Midwifery Council of Nigeria License",
    type: "License",
    issuingBody: "Nursing & Midwifery Council of Nigeria (NMCN)",
    issueDate: "2021-06-15",
    expiryDate: "2025-06-14",
    status: "Verified" as const,
    verificationHash: "0x7f3a9b2c4d5e6f1a8b9c0d1e2f3a4b5c6d7e8f9",
    credentialId: "NMCN/RN/2021/08754",
  },
  {
    id: "cred-2",
    name: "Basic Life Support (BLS)",
    type: "BLS",
    issuingBody: "American Heart Association",
    issueDate: "2024-01-20",
    expiryDate: "2026-01-19",
    status: "Verified" as const,
    verificationHash: "0x2b4d6f8a0c1e3d5f7a9b1c3d5e7f9a1b3d5e7f9a",
    credentialId: "AHA/BLS/2024/NG-4521",
  },
  {
    id: "cred-3",
    name: "Advanced Cardiovascular Life Support (ACLS)",
    type: "ACLS",
    issuingBody: "American Heart Association",
    issueDate: "2024-03-10",
    expiryDate: "2026-03-09",
    status: "Verified" as const,
    verificationHash: "0x1a3c5e7f9b1d3f5a7c9e1b3d5f7a9c1e3d5f7a9c",
    credentialId: "AHA/ACLS/2024/NG-3287",
  },
  {
    id: "cred-4",
    name: "Bachelor of Nursing Science (BNSc)",
    type: "Degree",
    issuingBody: "University of Lagos",
    issueDate: "2016-11-30",
    expiryDate: null,
    status: "Verified" as const,
    verificationHash: "0x9f8e7d6c5b4a3f2e1d0c9b8a7f6e5d4c3b2a1f0e",
    credentialId: "UNILAG/BNSc/2016/0452",
  },
  {
    id: "cred-5",
    name: "Trauma Nursing Core Course (TNCC)",
    type: "Certification",
    issuingBody: "Emergency Nurses Association",
    issueDate: "2023-08-15",
    expiryDate: "2025-08-14",
    status: "Pending" as const,
    verificationHash: null,
    credentialId: "ENA/TNCC/2023/NG-0189",
  },
  {
    id: "cred-6",
    name: "Pediatric Advanced Life Support (PALS)",
    type: "ACLS",
    issuingBody: "American Heart Association",
    issueDate: "2023-06-01",
    expiryDate: "2025-05-31",
    status: "Expiring Soon" as const,
    verificationHash: "0x4c6a8f0e2d5b7a9c1e3f5d7b9a1c3e5f7a9c1e3f",
    credentialId: "AHA/PALS/2023/NG-0756",
  },
  {
    id: "cred-7",
    name: "Infection Prevention & Control Certificate",
    type: "Certification",
    issuingBody: "Nigeria Centre for Disease Control (NCDC)",
    issueDate: "2022-09-20",
    expiryDate: "2024-09-19",
    status: "Expired" as const,
    verificationHash: null,
    credentialId: "NCDC/IPC/2022/0891",
  },
  {
    id: "cred-8",
    name: "Master of Science in Nursing (MSc)",
    type: "Degree",
    issuingBody: "University of Ibadan",
    issueDate: "2024-10-15",
    expiryDate: null,
    status: "Pending" as const,
    verificationHash: null,
    credentialId: "UI/MScN/2024/0098",
  },
  {
    id: "cred-9",
    name: "Neonatal Resuscitation Program (NRP)",
    type: "Certification",
    issuingBody: "American Academy of Pediatrics",
    issueDate: "2024-05-12",
    expiryDate: "2026-05-11",
    status: "Verified" as const,
    verificationHash: "0x5d7f9a1c3e5b7d9f1a3c5e7b9d1f3a5c7e9b1d3f",
    credentialId: "AAP/NRP/2024/NG-0342",
  },
];

export const credentialTypes = ["All", "License", "Certification", "Degree", "BLS", "ACLS"];

export const portfolioEntries = [
  {
    id: "port-1",
    title: "Hospital Management System Implementation",
    type: "Project",
    description:
      "Led the implementation of a digital hospital management system at LUTH, transitioning from paper-based to electronic health records across 12 wards. Trained 200+ nursing staff on the new system.",
    impactMetrics: "7,000+ patients impacted",
    startDate: "2023-01-01",
    endDate: "2023-12-31",
    featured: true,
    skills: ["Leadership", "Health IT", "Training"],
  },
  {
    id: "port-2",
    title: "Emergency Triage Protocol for Malaria Endemic Regions",
    type: "Publication",
    description:
      "Co-authored a peer-reviewed paper on optimizing triage protocols in malaria-endemic regions, published in the West African Journal of Nursing.",
    impactMetrics: "Cited 34 times across 5 countries",
    startDate: "2022-06-01",
    endDate: "2023-03-15",
    featured: true,
    skills: ["Research", "Emergency Triage", "Malaria Care"],
  },
  {
    id: "port-3",
    title: "Best Nurse of the Year — Lagos State",
    type: "Award",
    description:
      "Awarded Best Nurse of the Year by the Lagos State Ministry of Health for outstanding patient care and community health advocacy during the COVID-19 pandemic response.",
    impactMetrics: "Selected from 4,500+ nominees",
    startDate: "2022-05-01",
    endDate: "2022-05-01",
    featured: true,
    skills: ["Patient Care", "Community Health"],
  },
  {
    id: "port-4",
    title: "COVID-19 Isolation Ward Charge Nurse",
    type: "Leadership Role",
    description:
      "Served as Charge Nurse of the COVID-19 isolation ward at LUTH during the peak of the pandemic, managing a team of 15 nurses and overseeing care for 50+ patients simultaneously.",
    impactMetrics: "500+ patients cared for",
    startDate: "2020-04-01",
    endDate: "2021-03-31",
    featured: false,
    skills: ["Leadership", "Infection Control", "Crisis Management"],
  },
  {
    id: "port-5",
    title: "Community Maternal Health Outreach Program",
    type: "Project",
    description:
      "Designed and led a maternal health outreach program in underserved communities in Lagos, providing prenatal education and basic health screenings to over 2,000 women.",
    impactMetrics: "2,000+ women reached",
    startDate: "2022-08-01",
    endDate: "2023-07-31",
    featured: false,
    skills: ["Maternal Health", "Community Outreach", "Patient Education"],
  },
  {
    id: "port-6",
    title: "Certified Simulation Facilitator",
    type: "Certification",
    description:
      "Completed advanced training in clinical simulation facilitation, now conducting quarterly simulation-based training for emergency nursing staff at LUTH.",
    impactMetrics: "Trained 80+ nurses",
    startDate: "2023-09-01",
    endDate: null,
    featured: false,
    skills: ["Simulation", "Training", "Emergency Care"],
  },
];

export const portfolioTypes = ["Project", "Publication", "Award", "Certification", "Leadership Role"];

export const cpdActivities = [
  {
    id: "cpd-1",
    title: "Advanced Emergency Nursing Course",
    type: "Course",
    points: 12,
    date: "2024-11-15",
    provider: "NurseOS Academy",
    status: "Verified" as const,
    description: "Comprehensive course on advanced emergency nursing protocols and procedures.",
  },
  {
    id: "cpd-2",
    title: "Infection Control Workshop",
    type: "Workshop",
    points: 5,
    date: "2024-10-20",
    provider: "NCDC",
    status: "Verified" as const,
    description: "Workshop on latest infection prevention and control guidelines for healthcare facilities.",
  },
  {
    id: "cpd-3",
    title: "West African College of Nursing Conference",
    type: "Conference",
    points: 8,
    date: "2024-09-05",
    provider: "WACN",
    status: "Verified" as const,
    description: "Annual conference on nursing education and practice in West Africa.",
  },
  {
    id: "cpd-4",
    title: "Pharmacology Update for Nurses",
    type: "Course",
    points: 6,
    date: "2024-08-12",
    provider: "University of Lagos CPD Unit",
    status: "Verified" as const,
    description: "Update on new drug formulations and nursing considerations in pharmacology.",
  },
  {
    id: "cpd-5",
    title: "Trauma Care Seminar",
    type: "Seminar",
    points: 3,
    date: "2024-07-18",
    provider: "LUTH Training Division",
    status: "Pending" as const,
    description: "Seminar on advanced trauma care and mass casualty management.",
  },
  {
    id: "cpd-6",
    title: "Mental Health First Aid Training",
    type: "Workshop",
    points: 4,
    date: "2024-06-25",
    provider: "Mental Health Foundation Nigeria",
    status: "Verified" as const,
    description: "Training on providing mental health first aid in clinical settings.",
  },
  {
    id: "cpd-7",
    title: "Digital Health & Telemedicine Workshop",
    type: "Workshop",
    points: 4,
    date: "2024-05-10",
    provider: "Nigeria Health Innovation Hub",
    status: "Verified" as const,
    description: "Workshop on leveraging digital health tools and telemedicine platforms.",
  },
  {
    id: "cpd-8",
    title: "Maternal & Child Health Update",
    type: "Course",
    points: 5,
    date: "2024-04-02",
    provider: "NurseOS Academy",
    status: "Verified" as const,
    description: "Update on best practices in maternal and child health nursing.",
  },
  {
    id: "cpd-9",
    title: "Research Methodology for Nurses",
    type: "Course",
    points: 3,
    date: "2024-02-14",
    provider: "University of Ibadan",
    status: "Verified" as const,
    description: "Introduction to research methodology and evidence-based practice.",
  },
];

export const cpdTypes = ["All", "Course", "Workshop", "Conference", "Seminar"];

export const cpdPointsByType = [
  { name: "Course", value: 26, color: "#10b981" },
  { name: "Workshop", value: 13, color: "#14b8a6" },
  { name: "Conference", value: 8, color: "#0d9488" },
  { name: "Seminar", value: 3, color: "#059669" },
];

export const competencies = [
  {
    id: "comp-1",
    area: "Clinical Assessment",
    level: 4,
    levelName: "Proficient",
    lastAssessed: "2024-11-01",
    assessor: "Dr. Adebayo Ogundimu",
  },
  {
    id: "comp-2",
    area: "Medication Administration",
    level: 5,
    levelName: "Expert",
    lastAssessed: "2024-10-15",
    assessor: "Matron Folake Adeyemi",
  },
  {
    id: "comp-3",
    area: "Emergency Care",
    level: 5,
    levelName: "Expert",
    lastAssessed: "2024-11-10",
    assessor: "Dr. Chinedu Eze",
  },
  {
    id: "comp-4",
    area: "Patient Education",
    level: 4,
    levelName: "Proficient",
    lastAssessed: "2024-09-20",
    assessor: "Sr. Mary Okonkwo",
  },
  {
    id: "comp-5",
    area: "Leadership & Management",
    level: 3,
    levelName: "Competent",
    lastAssessed: "2024-08-05",
    assessor: "Dr. Aisha Bello",
  },
  {
    id: "comp-6",
    area: "Documentation & Reporting",
    level: 4,
    levelName: "Proficient",
    lastAssessed: "2024-10-01",
    assessor: "Matron Folake Adeyemi",
  },
  {
    id: "comp-7",
    area: "Infection Control",
    level: 5,
    levelName: "Expert",
    lastAssessed: "2024-09-15",
    assessor: "Dr. Ngozi Okafor",
  },
  {
    id: "comp-8",
    area: "IV Therapy",
    level: 5,
    levelName: "Expert",
    lastAssessed: "2024-11-05",
    assessor: "Dr. Adebayo Ogundimu",
  },
  {
    id: "comp-9",
    area: "Wound Management",
    level: 3,
    levelName: "Competent",
    lastAssessed: "2024-07-22",
    assessor: "Sr. Mary Okonkwo",
  },
  {
    id: "comp-10",
    area: "Maternal & Child Health",
    level: 2,
    levelName: "Advanced Beginner",
    lastAssessed: "2024-06-10",
    assessor: "Matron Folake Adeyemi",
  },
  {
    id: "comp-11",
    area: "Critical Care Nursing",
    level: 4,
    levelName: "Proficient",
    lastAssessed: "2024-10-28",
    assessor: "Dr. Chinedu Eze",
  },
  {
    id: "comp-12",
    area: "Pharmacology",
    level: 3,
    levelName: "Competent",
    lastAssessed: "2024-08-15",
    assessor: "Dr. Aisha Bello",
  },
];

export const competencyLevels = [
  "Novice",
  "Advanced Beginner",
  "Competent",
  "Proficient",
  "Expert",
];

export const competencyRadarData = competencies.map((c) => ({
  area: c.area.length > 15 ? c.area.substring(0, 15) + "…" : c.area,
  level: c.level,
  fullMark: 5,
}));
